### ISSUE TITLE
Instructions in Readme.md on how to include HF are incorrect

### ISSUE THREAD

**Issue by GazbonicAcid** [joshiejack/Harvest-Moon#100]
Instructions in Readme.md on how to include HF are incorrect.
I ran ./gradlew --refresh-dependencies -Dorg.gradle.jvmargs=-Xmx2G setupDecompWorkspace
This is the [console log](http://pastebin.com/Vkh3jwVk).
And this is my [build.gradle](http://pastebin.com/1fE5chVF).

**Comment by TehNut** [comment]
Wrong repositories block. You put it in the Buildscript repositories, not the project repositories. The README instructions are correct.

**Comment by GirafiStudios** [comment]
Yup, just like TehNut said :)
