### ISSUE TITLE
game crashing

### ISSUE THREAD

**Issue by devil1983** [joshiejack/Harvest-Moon#102]
[crash-2016-11-04_21.03.30-server.txt](https://github.com/PenguinSquad/Harvest-Festival/files/571580/crash-2016-11-04_21.03.30-server.txt)

at joshie.harvest.npc.entity.ai.EntityAISchedule.func_75246_d(EntityAISchedule.java:83)

What reason is this?

**Comment by joshiejack** [comment]
Honestly I've had a look and i'm not entirely sure. Was this consistent, easy way to recreate it?

**Comment by joshiejack** [comment]
No response in a month so closing.
