### ISSUE TITLE
Villagers despawn 

### ISSUE THREAD

**Issue by Rozzers** [joshiejack/Harvest-Moon#103]
We are having villagers despawning on the server. It seems random as to who it is. I have had Jenni and Jade despawn. Others have had Yulif and another Jim.

**Comment by joshiejack** [comment]
Nothing I can do, it will be another mod or server plugin.  There's no "despawn x npc" code. Something will be cleaning up persistent entities. Are you sure they dissapeared, try /hf npc sometimes they get lost somehow

**Comment by Rozzers** [comment]
Alright. Ill mess around and see whats causes it.

**Comment by joshiejack** [comment]
Closing as not sure if still an issue or even if, if it is something could even being to know where to fix.
