### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Jester0914** [joshiejack/Harvest-Moon#106]
Okay, so i know what's causing the crash, I'm on a lan server hosted by myself, 

I7 6700k
GTX960 4gb
MSI Z170apcmate motherboard

And every time we pick up a Weed, it kicks either her or i (Relative to whomever picked it up) and basically will not let us rejoin, so long as we do not equip said "Weed" we are usually fine.

**Comment by joshiejack** [comment]
And what is the actual crash?

**Comment by Jester0914** [comment]
[crash-2016-11-18_01.50.11-client.txt](https://github.com/PenguinSquad/Harvest-Festival/files/599647/crash-2016-11-18_01.50.11-client.txt)
[crash-2016-11-18_01.52.10-client.txt](https://github.com/PenguinSquad/Harvest-Festival/files/599648/crash-2016-11-18_01.52.10-client.txt)
[crash-2016-11-18_01.54.57-client.txt](https://github.com/PenguinSquad/Harvest-Festival/files/599649/crash-2016-11-18_01.54.57-client.txt)
[crash-2016-11-18_02.42.21-client.txt](https://github.com/PenguinSquad/Harvest-Festival/files/599651/crash-2016-11-18_02.42.21-client.txt)
[crash-2016-11-18_02.44.43-client.txt](https://github.com/PenguinSquad/Harvest-Festival/files/599650/crash-2016-11-18_02.44.43-client.txt)

**Comment by Jester0914** [comment]
Those are the crashes i have, this should help with repeating the issues. if you'd like I can screen cap the culprit in game as well

**Comment by Jester0914** [comment]
![image](https://cloud.githubusercontent.com/assets/23549569/20426723/6e71b78e-ad4e-11e6-9a41-739d03d3b386.png)
![2016-11-18_05 17 19](https://cloud.githubusercontent.com/assets/23549569/20426731/7a236f14-ad4e-11e6-85c1-5c87781564f8.png)
![2016-11-18_05 17 29](https://cloud.githubusercontent.com/assets/23549569/20426730/7a1d48fa-ad4e-11e6-8b92-2b4fdf462603.png)
![2016-11-18_05 17 35](https://cloud.githubusercontent.com/assets/23549569/20426729/7a1cd0b4-ad4e-11e6-931e-61f50061e20e.png)

**Comment by Jester0914** [comment]
[crash-2016-11-18_05.17.41-client.txt](https://github.com/PenguinSquad/Harvest-Festival/files/599675/crash-2016-11-18_05.17.41-client.txt)

**Comment by joshiejack** [comment]
Can you confirm this happens with hf on its own pls.  Also what is ren,
it's crashing with that. Googling makes me believe it's the real first
person render mod. Try removing that.

**Comment by Jester0914** [comment]
Absolutely happy to do that, I have A few errands to run and I will do that
when I return

**Comment by Jester0914** [comment]
Okay, so I had my gf do as you asked, and it fixed the problem.  No crash
