### ISSUE TITLE
Crash when opening inventory to page 5 where harvest festival items are stored.

### ISSUE THREAD

**Issue by xKinqMagnus** [joshiejack/Harvest-Moon#108]
I can't read crash logs that well, but it says that it couldn't find certain items? It doesn't look like I could find any dependencies. https://gist.github.com/xKinqMagnus/e440cea59a4aeb2c8db3642746102246

**Comment by joshiejack** [comment]
java.lang.NullPointerException: Rendering screen
	at net.fexcraft.mod.frsm.util.custom.CT$CTS.func_78016_d(CT.java:113)

Clearly a crash with "Fexcraft" whatever that is.
