### ISSUE TITLE
Clicking On Shop Item Causes Game Crash

### ISSUE THREAD

**Issue by ano19920** [joshiejack/Harvest-Moon#109]
I can buy things, but when I click on the item that is for sale, something is activated. I am in creative mode and it acts like I am about to edit the item or sale--maybe? Whatever is trying to happen, it keeps crashing me out of the game. I have no idea if this is from your mod or a different mod is interfering, but these are 2 crash reports from me doing the same thing: right click on an item in a shop.

[crash-2016-11-22_20.06.18-client.txt](https://github.com/PenguinSquad/Harvest-Festival/files/608017/crash-2016-11-22_20.06.18-client.txt)
[crash-2016-11-22_20.22.04-client.txt](https://github.com/PenguinSquad/Harvest-Festival/files/608016/crash-2016-11-22_20.22.04-client.txt)

**Comment by GirafiStudios** [comment]
This is caused by NoMoreRecipeConflict. Trying removing that and see if it solves your issue :)

**Comment by ano19920** [comment]
Problem solved! But I guess nothing was even trying to happen, though. How do I modify shops, then?
