### ISSUE TITLE
Crash with trough

### ISSUE THREAD

**Issue by Tedyhere** [joshiejack/Harvest-Moon#110]
Getting a crash with Harvest Festival when having the Trough in hand.

Crashes to Desktop

https://gist.github.com/Tedyhere/773898e9897138aed0afe67e62914433

Thank you for reporting!
---

 * Please upload your crash reports or logs to https://gist.github.com or similiar sites, don't just paste it in raw!
 * If the issue is not a crash, please provide your fml-client-latest.log or fml-server-latest.log
 * Before reporting your issue, please make sure it have not already been reported.
 * Make sure you have the latest version of Harvest Festival, since your issue might already have been fixed!
 * Preferably provide us with what Forge version you are using. 
 * If the issue is between Harvest Festival and another mod, please inform what version of the mod you are using. Also make sure the other mod is updated to latest version.
 * Please check out https://github.com/PenguinSquad/Harvest-Festival/blob/1.10.2/PLANS.md, before making any suggestions!

**Comment by TehNut** [comment]
What is `realrender.REN`?

E: It's Real First Person Render. Does it happen without that?

**Comment by joshiejack** [comment]
that's the first person rendering mod

**Comment by joshiejack** [comment]
https://github.com/PenguinSquad/Harvest-Festival/issues/106  Had the same
crash with that mod

**Comment by Tedyhere** [comment]
Ok I will advise removing it since it's client side and copy the issue over to them?

**Comment by Tedyhere** [comment]
Removing FPR fixed the issue.  Thanks

**Comment by Tedyhere** [comment]
Removed Third Person Render thingy fixed it. Thanks everyone, friend was pulling their hair out
