### ISSUE TITLE
ItemIngredients not compatible with AppleCore

### ISSUE THREAD

**Issue by squeek502** [joshiejack/Harvest-Moon#111]
ItemIngredients overrides `onItemUseFinish` and calls the `int, float` version of `FoodStats.addStats`, which bypasses AppleCore's OnFoodEaten event ([which expects the `ItemStack` version of `FoodStats.addStats` to be called instead](https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore)).

As far as I can tell, the entire `onItemUseFinish` override is unecessary, as it's identical to [the implementation in the base class that it extends](https://github.com/PenguinSquad/Harvest-Festival/blob/f8b6340329c3565ea5c154a88e22827f52151bc7/src/main/java/joshie/harvest/core/base/item/ItemHFFood.java#L69-L80), apart from the version of `addStats` that is called. If I'm not missing something, the fix could be as simple as removing the implementation of `onItemUseFinish` in `ItemIngredients`.

Relevant code: 
- https://github.com/PenguinSquad/Harvest-Festival/blob/6adc58e18004bad8b106aec7819acd640676f121/src/main/java/joshie/harvest/cooking/item/ItemIngredients.java#L99

**Comment by joshiejack** [comment]
yea i know. It never used to extend itemfood, and i made it do that so i
didn't have to do special support for applecore.  I guess i accidentally
left that method in =p
