### ISSUE TITLE
Request - I love this mod concept but is there a way you could make it modular?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [joshiejack/Harvest-Moon#114]
A modular mod is broken into features and basically if a player is not seeking a feature it could easily be tweaked to turn a function on or off. I hope I am not intruding but I am mainly interested in the aspect of gold system and shop system. I run a poke-cube server and I deeply need a way to run a custom shop that is straight forward and not convoluted. Also how do you obtain gold? Are vanilla mods disabled on launch? do you get gold = to zombies killed? can you only get gold based on sales? Your mod looks epic but I see very little descriptions on its creation. If you want I can help you maintain it a bit as I have time or at the very least make sure that users understand the different intentions of your mod.

**Comment by joshiejack** [comment]
Sorry not possible everything is so tied in to each other it would be too much hassle to maintain. To ensure each part is independent. For example, can't disable npcs, need them to progress, disabling crops or animals breaks cooking, as well as breaking the tutorial.

If you just want a specific thing you'll have to use a different mod.
