### ISSUE TITLE
Right-click Harvest doesnt give Scythe XP

### ISSUE THREAD

**Issue by Peach774** [joshiejack/Harvest-Moon#115]
Using right-click harvest on regrowable crops does not give xp. Either the regrowable crops need to be able to be broken but instead of being destroyed they go back to the regrowth stage, or they need to give the scythe xp because currently it takes forever to level the scythe up.

**Comment by joshiejack** [comment]
Sorry but no. The sickle has no right click functionality. It makes no sense that right click would level it up when you need nothing to right click harvest. Just break a bunch of leaves or grass with it to level it fast.

**Comment by Peach774** [comment]
I tried breaking grass. It isnt getting any XP. Also, if rightclick isnt built in, then how are corn and strawberries supposed to be regrowable?

**Comment by joshiejack** [comment]
I mean that you can hold any item or none at all to right click harvest. You don't need a sickle.

**Comment by Peach774** [comment]
But how do I get sickle XP then? I can only egt it from dead crops and left-click harvest crops. Leaves and grass dont work (i didnt know they were supposed to)
