### ISSUE TITLE
Snow disappearing over night

### ISSUE THREAD

**Issue by Lodugh** [joshiejack/Harvest-Moon#120]
I dont think that this is intended, right? :D 
I have the ninth of Winter and it still happens every night. The feeling in the winter is great, but that kinda breaks it a bit.
I use Harvest Festival 0.5.22 on Forge 12.18.3.2185 with a bunch of other mods, but I could reproduce the bug with Harvest Festival by itself.
Hope you can fix that. Keep up the great work! :)

[fml-client-latest.txt](https://github.com/PenguinSquad/Harvest-Festival/files/670787/fml-client-latest.txt)

**Comment by joshiejack** [comment]
Last I tried this, it would only melt in seasons other than winter. I'll have to test it again.

**Comment by joshiejack** [comment]
Works in 0.5 and 0.6 for me
