### ISSUE TITLE
Not Here! You do not have permission to build here Bug

### ISSUE THREAD

**Issue by Nycozi** [joshiejack/Harvest-Moon#123]
Hey ive encountered a bug/problem on a server im currently playing on. After we updated to 0.6.8 and logged in i can't place any buildings in my village it says "Not Here! You do not have permission to build here" and Im at a loss as to what to do, ive tried going else were to see if im able to build and i am, it seems like ive lost ownership to my own village

Current Version 0.6.8

**Comment by DcNdrew** [comment]
Don't you have spawn protection or something?
I'm searching this in the code, but I found one thing yet, this error based on the Minecraft's basic permission stuff.

**Comment by joshiejack** [comment]
Interesting that you're on a version that doesn't exist.

**Comment by DcNdrew** [comment]
It can be 0.5.8, but in that case it's a bit outdated.

**Comment by joshiejack** [comment]
Yeah I knew what they meant. Just found it funny.

**Comment by reddler97** [comment]
i am getting this message too.....i am close to spawn, however i'm playing single player so it wouldn't make sense for it to be spawn protection.................i did get it to work though be going into creative

i think i am playing on 0.5.22, ........ hard to tell since i am playing on a modpack i didn't put together

**Comment by joshiejack** [comment]
I am going to close this for now. When I release 0.6 of the mod (hopefully in the next few weeks...), if this still occurs please let me know.

**Comment by alicheek** [comment]
Hey this issue is still around the version of farming festival mod is 0.5.27 which is the farming valley modpack version 0.8.0

**Comment by junny2233** [comment]
Hello im having this issue with the version of the modpack farming valley 0.8.0 any idea how to fix it?

thank you!

**Comment by TheOnlyMrCat** [comment]
I have this issue too (Farming valley modpack)

**Comment by WebSurfinMurf** [comment]
Ditto, I downloaded the latest from the web site "Farming Valley Modpack".
We did NOT start a server, instead we started a single player game then "open to lan".   The person starting the world has no issue, I join the world and I can't build.

**Comment by ChaosB** [comment]
Just reload the world and it should work
