### ISSUE TITLE
Would love to help

### ISSUE THREAD

**Issue by JeffersonCalaway** [joshiejack/Harvest-Moon#124]
Sorry if this is the wrong spot, since it's not actually an issue, but it seemed like you were suggesting this on the forum post. I have a history with coding, enough to do grindy code monkey sort of work, and I actually work as a graphic designer. If there's a proper email or something I could send a portfolio to, I think I could be useful. Most notably I think the animals could use work, but characters too (given the variety in skin quality/detail). Any other sort of work I'm open to it. I think this is a mod I'd like to help be the best it could be.

**Comment by joshiejack** [comment]
I'm actually really happy with the animals/npcs.
