### ISSUE TITLE
A few Questions...

### ISSUE THREAD

**Issue by jelaw21** [joshiejack/Harvest-Moon#126]
I am not sure where to post this to get a timely response. I have one aspiring youth who racked up an entire season in a day on my SMP server. Is there a way to set the seasons day? If not, are the turnips able to grow in any season?  I have tried to update HF-Calendar.dat but the server keeps overriding on launch, so this has to be stored in a config I can't find?  Please help.

**Comment by joshiejack** [comment]
There should be /hf day and /hf season commands. But there is some mod that makes these not work, and knowing my luck I bet you have that mod.
