### ISSUE TITLE
Carpenter won't spawn

### ISSUE THREAD

**Issue by Battleship2424** [joshiejack/Harvest-Moon#127]
The carpenter building refuses to spawn when I use the blueprint. After I creatively spawned the building and the carpenter himself, the blueprints started working. I'm using the farming valley pack v:0.6.9 using harvest festival 5.22.

**Comment by joshiejack** [comment]
This makes zero sense whatsoever and doesn't happen to me. Also FYI that pack has inventory tweaks which is known to be rather buggy in the current versions.

**Comment by Battleship2424** [comment]
I created a server for the mod which resolved but created more problems. The carpenter problem went away, however, I was having a bug where I could see the items I was receiving but touching my inventory deleted the item. This is related to inventory tweaks I would think. This was also only client side as my friend had no problems. The root of the problem here was Inventory Tweaks I belive as you mentioned. I was having other problems but are unrelated.
