### ISSUE TITLE
[Suggestion] Right click building sign to teleport or spawn in missing npc

### ISSUE THREAD

**Issue by Rozzers** [joshiejack/Harvest-Moon#131]
With there being a problem with NPCs disappearing or respawning in caves below their respective houses (sometimes). Was thinking that right clicking the sign would be a good way to get them to spawn back in or teleport back to the house. Maybe on top of the player when sign is right clicked just so it won't go back underground to a cave by chance.

**Comment by joshiejack** [comment]
NPCs don't spend all their time in their houses, they walk around and visit other npcs/buildings during their off hours. And should make their way home in time for work, if not they should teleport. 

Not sure how a npc would end up in the cave below, i think that could only really happen with yulif when he's building.

I don't mind the idea of being able to recall npcs though. Just the sign method wouldn't really work as not every building has a sign. I guess each shop does. Plus if it got blown up by a creeper would be an issue. I guess could replace it but that feels weird. If you can think of another thematic way, I could do it.

**Comment by Rozzers** [comment]
Unless the building was made indestructible but that could be a hassle, or just the sign indestructible. I do usually have mobgriefing false for reasons like that. I'll ponder and ask around if someone has a reasonable idea.

**Comment by Rozzers** [comment]
What about having a command?

Something like /HF check NPCs
Or whatever may work better or even have it be the npc name instead - /HF check yulif

Then it would put yulif at the house or at the player in the town the command was run.

**Comment by ecoay** [comment]
I am making a Sky Block modpack with harvest festival and the carpenter tends to just wander off into the void lol. Something to bring him back would be helpful

**Comment by Kfrost084** [comment]
I think that might be the same reason i keep loosing towns folk as well. It gets rather annoying having to repeatedly keep cheating the NPCs in. For some reason they don't respawn when i go to sleep. Maybe add a "Ring For Service" bell thingy that forces them to teleport or respawn if a check for the NPC fails.

**Comment by GirafiStudios** [comment]
Thanks for your suggestion!
As Joshie already explained in his comment, the sign method wouldn't really work since not all buldings have a sign.
