### ISSUE TITLE
Crash related to Iron Chests(?)

### ISSUE THREAD

**Issue by ghost** [joshiejack/Harvest-Moon#132]
Got this crash: https://gist.github.com/Canatee/8681ad5520b6fbc2e786e1d95e607fac
Just after placing an incubator next to an iron chest from the mod Iron Chests like this, see pic.  

![2017-02-04_10 14 30](https://cloud.githubusercontent.com/assets/25546019/22617371/90eed06e-eac3-11e6-8e4a-6be766d128c1.png)

Have tried to recreate, without luck. 
Unsure if it's HF side or IC chest, so forgive me if it's wrong to report it here. 

MC 1.10.2
Forge 12.18.2.2171
Harvest Festival 0.5.22
Iron Chests 7.0.11.797

**Comment by joshiejack** [comment]
I added a check, should hopefully be fixed in 0,6
