### ISSUE TITLE
Weather effects out of sync with season displayed in HF calendar HUD

### ISSUE THREAD

**Issue by PorkchopFu** [joshiejack/Harvest-Moon#134]
[Harvest-Festival-1.10.2-0.5.22.jar & 12.18.3.2221]

I added time to my dedicated server via '/time add <###>' to 'skip' winter. The calendar HUD now displays 'Summer', but the ground is still snowy and the blizzard effects and falling snow persist as if Harvest Festival still thinks it is winter. Is there a way to 'reset' or 'resync' the seasons without damaging the world?

Otherwise this is a great mod. Keep up the good work.

Thank you for reporting!
---

 * Please upload your crash reports or logs to https://gist.github.com or similiar sites, don't just paste it in raw!
 * If the issue is not a crash, please provide your fml-client-latest.log or fml-server-latest.log
 * Before reporting your issue, please make sure it have not already been reported.
 * Make sure you have the latest version of Harvest Festival, since your issue might already have been fixed!
 * Preferably provide us with what Forge version you are using. 
 * If the issue is between Harvest Festival and another mod, please inform what version of the mod you are using. Also make sure the other mod is updated to latest version.
 * Please check out https://github.com/PenguinSquad/Harvest-Festival/blob/1.10.2/PLANS.md, before making any suggestions!

**Comment by joshiejack** [comment]
Weather is set seven days ahead of time. So you'll still get the weather that was planned in winter (for 7 days).

**Comment by PorkchopFu** [comment]
That makes me feel much better, thank you!
