### ISSUE TITLE
[Issue] Buildings can't be built

### ISSUE THREAD

**Issue by ghost** [joshiejack/Harvest-Moon#136]
Good morning/evening/night.
Recently, i started playing the mod and i am really enjoying it, but there is an issue that is making me get really upset, i can't build a second carpenter shop, i have alredy removed the first from the map, cleaned up the space for the new one, killed the carpenter and his sister and it still does not let me build a second carpenter shop, what can i do to fix it?

**Comment by joshiejack** [comment]
You can only have one building per town. Destroying the blocks means nothing. The only way now is to move somewhere else.

**Comment by hakanai** [comment]
I found I can't even build the first one.

**Comment by joshiejack** [comment]
Please try 0.6 @trejkaz if still not working open a new issue
