### ISSUE TITLE
Request Config for Seasons not being required.

### ISSUE THREAD

**Issue by Malus-Lupo** [joshiejack/Harvest-Moon#137]
I have a request, I would like to use your mod in a Adventure Style Pack how ever I really need players to be allowed to farm any kind of crop at any time of year. The pack is themed in space and there really are no seasons in space. I would go with another mod but really yours is just the best, the animals look awesome, the crops look and work so cool and I want to limit what people can craft but you do not need to craft anything to cook and use the food in your nod so its perfect. So my request is a config setting, that can be false by default, that would let any crop be planted any time of year.

Thanks for reading ether way! Note I also posted this on Minecraft Forums before remembering Gethub.

**Comment by joshiejack** [comment]
You're better off using another mod. Currently this would involve a lot of rewriting of the code which I'm not willing to do yet. A lot of other things not just the crops rely on the seasons.
