### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by ShuzzDE** [joshiejack/Harvest-Moon#138]
Hi!
I'm currently working on a german translation for the mod.
I extracted the en_US.lang from the .jar file that was distributed with the pack "Farming Valley" (0.5.23).
It had to be that specific version because I want to play that pack with my kids and they don't speak English, yet.

Would you be interested in that .lang file? If so, please leave a note here and I'll create a pull request once I'm done.

**Comment by joshiejack** [comment]
Yep, when you do make sure to pr to the 0.5 branch.

**Comment by ShuzzDE** [comment]
https://github.com/PenguinSquad/Harvest-Festival/pull/139 was accepted, closing this issue.
