### ISSUE TITLE
 Harvest Festival 0.5.25 mod translation into Brazilian Portuguese

### ISSUE THREAD

**Issue by Brittahplay** [joshiejack/Harvest-Moon#145]
Below is the translation of the mod Harvest Festival 0.5.25 (Brazilian Portuguese)

[pt_BR.lang.txt](https://github.com/PenguinSquad/Harvest-Festival/files/949226/pt_BR.lang.txt)

**Comment by joshiejack** [comment]
It should be sent as a pull request not like this.

**Comment by Brittahplay** [comment]
Sorry.
