### ISSUE TITLE
Villagers till branches, stones, and shipment box.

### ISSUE THREAD

**Issue by Lance5057** [joshiejack/Harvest-Moon#15]
Villagers seem to treat branches, stones, and the shipment box as if its farmable and till it into farmland. I keep losing my shipment box because of it.

**Comment by joshiejack** [comment]
What on earth. I'll have to check the villager ai to see what they're doing...

**Comment by joshiejack** [comment]
Oh wait. Maybe this is that bug, that I fixed earlier too. Not what you think it is xD. <<< was confused because villagers don't till farmland. Is it wet soil? If so that's fixed.

**Comment by Lance5057** [comment]
The shipment crate was no where near water so it shouldn't have been wet.

**Comment by joshiejack** [comment]
Let me know if you run in to this issue again, I haven't. I've noticed some crops reappearing as dead though... >.>, unless I just forgot about them xD.
