### ISSUE TITLE
Harvest Goddess has no text?

### ISSUE THREAD

**Issue by HermitMandy** [joshiejack/Harvest-Moon#150]
Hello! Finally got a chance to download and play the mod in the Farming Valley modpack for a bit the past few days. Got my house mostly built and went to summon the goddess to get going, only to discover she has no text. I tried sleeping the night, exiting to the menu, closing and restarting the game, even downgrading some versions in case it was something going on with the current. Theres no crashes, just a little lag from Fast leaf decay, and everything else so far seems to be working as it should.
Quite frankly I'm stuck on what to do, as the pack is essentially unplayable for me at this point.

**Comment by joshiejack** [comment]
Can you prove this please with a video. Noone has had this issue. And I've watched countless people playing farming valley.

**Comment by HermitMandy** [comment]
https://youtu.be/vWMK5cpebVI

Forgot to re-download the lastest update before filming, but it does the exact same thing.

**Comment by joshiejack** [comment]
Something is even broken with that heart. Some other mod you have will be causing this. I'm guessing the text is actually there, it's just black. Did you add/change anything from the default farming valley?

**Comment by HermitMandy** [comment]
This outta be fun finding out which one is causing it. Surprised nobody else playing the pack has this issue.

When I find it, I'll be sure to let you know which one it is.

**Comment by joshiejack** [comment]
Should try HF on its own to see if it even is another mod. If not, the only difference I can see is ya using mac.

**Comment by HermitMandy** [comment]
Just loaded up the Stumpt Village pack I was playing in last night. Text is showing fine there, so it's some kind of strange conflict within the Farming Valley pack.

**Comment by GirafiStudios** [comment]
Thanks for your report!
As this is not reproducible with the latest version of Farming Valley, I will close this for now.
Please open a new issue, if you still have this issue. Preferably with the mod/mods that is causing the problem listed.
