### ISSUE TITLE
Cooking Festival Issues

### ISSUE THREAD

**Issue by Elvarion** [joshiejack/Harvest-Moon#151]
* Harvest-Festival-1.10.2-0.6.0-213 | Tested on 215 also
* Forge-1.10.2-12.18.3.2281-universal
---

On the server the event does not seem to start (No letter arriving)
On Singleplayer the letter arrives but when trying to accept the invitation you get disconnected from singleplayer. Log from when being kicked is below.

https://pastebin.com/bLb7yb2E

Modlist
https://pastebin.com/xauQefdy

**Comment by Andvee** [comment]
Expanding on open issue.

forge-12.18.3.2297
harvest-festival-1.10.2-0.5.0-218

no crash log.

Cannot participate in the cooking festival. After submitting a dish Jenni will display "No meals have been placed on any of the plates!"

Screenshots -

![hf bug3](https://cloud.githubusercontent.com/assets/8715158/26519166/e7fac218-4271-11e7-9ed0-a86f2ac11514.png)

![hf bug2](https://cloud.githubusercontent.com/assets/8715158/26519170/f811d556-4271-11e7-92ff-68391778cc5b.png)

**Comment by joshiejack** [comment]
The festival isn't fully implemented yet. Only really the cow festival is done.
