### ISSUE TITLE
Blueprints do not function and Crash the game by talking to Yulif.

### ISSUE THREAD

**Issue by halet707** [joshiejack/Harvest-Moon#152]
I can't see any ghost image when I am holding a blueprint.
After I confirmed to build,the game will crash every times if I talk to Yulif.
These problems happen on mod version 0.5.4 to newest but the version 0.5.3 is normal.

Here is the crash report
[https://gist.github.com/halet707/fb493820d38c92b8f9d583c4c6ee322f](url)

**Comment by GirafiStudios** [comment]
Thanks for your report!
Unfortunately your gist link is no longer available & I can't reproduce this.
Please open a new report if you can reproduce this with the latest 0.6 version of Harvest Festival.
