### ISSUE TITLE
Crops stop growing randomly in Season

### ISSUE THREAD

**Issue by Xeven-Shimizu** [joshiejack/Harvest-Moon#153]
Mod Version: Harvest-Festival-1.10.2-0.5.25
Forge Version: forge-1.10.2-12.18.3.2234-universal
Note: This is on the Farming Valley modpack from the Curse Launcher(Now the Twitch Launcher?).

Randomly some crops will freeze up, even though it is still their season to grow. I've had wheat stop right before it's finished, letting more than 10 days pass after their last stage of growth and it just didn't finish growing. I've also had potatoes that stopped growing on their final stage and refused to grow. And I have watered them every day, not really sure what would cause this. It is a server ran by a friend who brings it up when we're around and leaves it up overnight sometimes.

I'm not sure what causes this or how to fix it (We usually destroy the plants and spawn in replacement seed) and I couldn't find anyone with similar problems so any help would be appreciated.

**Comment by joshiejack** [comment]
was fixed in 0.5.26
