### ISSUE TITLE
Canteen is being replaced with Water Bottle

### ISSUE THREAD

**Issue by JamesPierce82** [joshiejack/Harvest-Moon#154]
When attempting to fill a canteen from a cauldron, it replaces the canteen with a waterbottle full of dirty water.

**Comment by GirafiStudios** [comment]
Thanks for the report!
This is a problem with Tough as Nails.
You can go report it to them over at https://github.com/Glitchfiend/ToughAsNails. Keep in mind that Tough As Nails is not currently actively developed, but I'm sure they will eventually get around to it.
