### ISSUE TITLE
Buildings not recognized after leaving world 

### ISSUE THREAD

**Issue by Scorpinox** [joshiejack/Harvest-Moon#155]
In harvest festival 0.6, I have experienced a problem where building stop being recognized after leaving my world. Before leaving the world, I saw Yulif offering the building options I expected (including the mining hill and cafe). Additionally, I am prevented from putting the same buildings in the local area, as I believe I should be. However, after restarting, Yulif offers only the general store and poultry/animal farm, and if I spawn in the autobuilder items, I can build near the old shops. Replacing the shops using the autobuilders temporarily fixes it, but it is lost again after the world is reset. I am playing the Farming Valley modpack, but with Minecraft Comes Alive added and Harvest Festival updated to 0.6. Any ideas what could be causing this?

Also: Log files do not mention Harvest Festival except for a missing mcmod.info file and the timing data.

**Comment by joshiejack** [comment]
Was this previously a 0.5 world, if so try deleting the hf-data file in your save. If so, what version of 0.6, cause thought I fixed it.

If it wasn't an upgraded world, I'm clueless.

**Comment by Scorpinox** [comment]
Yes it was an upgraded world, and that appears to have fixed it. Thanks for helping me, and thanks for this incredible mod!
