### ISSUE TITLE
[suggestion] a stand-by mode for the mod

### ISSUE THREAD

**Issue by Alessandro404** [joshiejack/Harvest-Moon#156]
Hi! loving the mod, and as a big fan of harvest moon, i've passed years trying to building modpacks with different mods hoping to obtain the feeling (and the intermod functionalities) that this mod have, and i'm absolutely stunned on the work you guys did here.

Reading the config for 6.0 i'm happy to see a long list of customization to turn off most of the more "total conversion-ish" features of the mod, but i'm here to ask about a config that totally silence the mod.

the thing is, As i love this mod, I am part of a (very small i guess) playerbase that use the same world from the beginning (years and years, since vanilla beta and the first cobblestone buildings to nowm modded to hell and back), and I like the idea to play this mod to his full extent, and after a while "pause" his features, maybe returning to my principal house, just for changing what i do and mantain mc fun. 

Normally, removing the mod can corrupt worlds but with a little patience and know how (and sometimes an extesive use of mcedit) it can be done, so when i removed for example local weather years ago, the world and gameplay simply adapted. 

With THIS mod, however, the idea to removing what i have done simply doesn't appeal me. The progression, the npcs, the beautifulness and the fact that i WANT to return to "play" harvest festival  when i want to take a vacation from my factory is just like having a minigame inside the principal game.

I know that from an "immersion" prospective it requires that a player accepts the fact that "seasons" can be toggled on and off and thing like this, but from a gameplay prospective, it could make this mod much more bearable as an expansion of the normal gameplay, something you could leave in a distant valley waiting for the next update, after hours and hours of gameplay 😄 (and to return when you feel so)

I know this request could be seen as controversial, and my english is not good enough to be sure i'm not  giving the idea i want to disable part of this mod for using them in a way that ruins the vision of the modder. I just want to play it to his fullest, and then pause it when i feel i need to make something else.

Thanks in advance for reading

**Comment by joshiejack** [comment]
I'm sorry, I don't understand what you're asking.

**Comment by Alessandro404** [comment]
A config to remove every single feature (i'm thinking about seasons, for example, that change how snow function in overworld) of the mod, so when a player stops playing this particular mod he can return to a more vanilla gameplay, without removing the mod, and is free to re-enable those things for when he want to play again with harvest festival.

Basically a pause button for everything, maybe crops growing and animal feeding too. Just like not playing the game on the gameboy and instead play something else

**Comment by joshiejack** [comment]
That's the weirdest request ever. Not gonna happen sorry.

**Comment by Alessandro404** [comment]
oh no problem
