### ISSUE TITLE
incompatibility with simpleDimensions

### ISSUE THREAD

**Issue by Alessandro404** [joshiejack/Harvest-Moon#157]
Sleeping in a dimension provided by simpleDimensions does not change the day, it simply reset the clock to 6:00 AM.

I made a guess, testing a little. It is of course not necessarly right.
The problem is that those dimensions are not syncronized with the overworld's clock, so sleeping here does put the timer at 6:00, but the "change of the day" triggers only if the clock is precisely 6:00 ON THE OVERWORLD. (similar to when skipping the precise minute with /time add)

made another test, sleeping in a dimension that is syncronized with the overworld (nomadic tents dimension) and it changed the day normally.

This make playing in those dimension impossible, because unless changing seasons or days with commands, the time is effectively frozen unless the players doesnt sleep

**Comment by joshiejack** [comment]
You can only make towns in the overworld anyway. So something handling time weirdly isn't something I'm interested in supporting.
