### ISSUE TITLE
Interaction Issue With Progression Mod

### ISSUE THREAD

**Issue by Slither88** [joshiejack/Harvest-Moon#158]
I have been trying to get the progression mod to pick up when a specific ore node is broken and then drop an item or set thereof. The problem is that I can only ever get the node to drop something else if I tell it to ignore state. I guess because you are randomly "rotating" the block for a more diverse look checking the state means that if the node you are breaking is not in the exact same "rotation" as the one you selected as part of the requirements it will not count as a valid break of that node.

I hope this makes sense. But I will give a scenario to try and make it as clear as possible:

Lets say I want to have the copper node also drop Tin Ore from another mod. So I select the condition of "Break Block" and choose "Block Stacks", then I select the copper node. If I leave everything as is, it will have the "match state=true". Then I select the "Give Item" reward and select the tin ore. When I break a placed node it only drops the copper ore from Harvest Festival. But when I go back and make "match state=false" then it does drop the tin ore. The problem with this of course is that it drops the tin ore for every node in harvest festival. I have tried everything I can think of and nothing "isolates" just the one node.

I am only posting this here because using this for most other blocks I have tried works perfectly, it only has an issue with the nodes. Maybe I am just doing something wrong?

**Comment by GirafiStudios** [comment]
Thanks for your report!
I was able to reproduce this a while back with HF 0.5, but can't reproduce it now with HF 0.6.
Please open a new issue, if you can still reproduce this in 0.6. Another option is to DM me on Discord, if that is easier for you :)
