### ISSUE TITLE
Sleep doesent refill Hunger, if Morpheus is installed on the Server

### ISSUE THREAD

**Issue by feuerball11** [joshiejack/Harvest-Moon#159]
Used Version: Harvest-Festival-1.10.2-0.6.0-218 (Manualy patched int he Modpack) 
Modpack Used: Farming Valley (https://mods.curse.com/modpacks/minecraft/254202-farming-valley)

Reproduction: 
- Start a new server with the modpack
- Be at least 2 players on the server
- Sleep with only 1 Person

Result: 
- Your hunger wont get refilld, but a new day starts.

Comment: 
I searched through your code, and the code of Morpheus. It seems that Morpheus uses setWorldTime. So it seems thet onWakeUp (What youre using for the hunger refill) isnt triggered. 
But i'm not a Mod Developer, so i cant tell ^^ just what i saw as an unexperienced Pogrammer ^^

**Comment by JamesPierce82** [comment]
It's definitely possible. I'm not a dev, and I haven't looked at Morpheus, but this sounds plausible. 

I can vouch for this being an issue though, as we take turns rotating on and off for hunger refill as needed. Thankfully we only have a few players and we're able to handle doing that. I can't imagine trying to do this with a larger server.

**Comment by joshiejack** [comment]
I override the morpheus handler btw https://github.com/PenguinSquad/Harvest-Festival/blob/1.10.2-0.6.X/src/main/java/joshie/harvest/plugins/morpheus/SleepHandlerOverworld.java

Because morpheus wasn't waking players up automatically :package: 
I know the 'issue' (although not really an issue) is there though.

**Comment by JamesPierce82** [comment]
"I know the 'issue' (although not really an issue) is there though."

Are you suggesting the behaviour is intended then? Just clarifying to make sure we understand. :)

**Comment by joshiejack** [comment]
No not saying it's intended. Just that it's not a huge deal (aka game breaking)

**Comment by feuerball11** [comment]
"I override the morpheus handler btw"
Thats interesting, didnt see that. 

Then i have sadly no idea why it could bug around O.o 

I want to start with minecraft modding one day, but i think, fixing bugs in a huge project like that, isnt that good of an idea  ^^

But i'm coriouse, maybe i research a bit about that, maybe i find something.

something that works with morpheous without ovveriding would be nice ^^
