### ISSUE TITLE
Crash After Reloading World After Entering/Exiting a dimension (Mining Hill)

### ISSUE THREAD

**Issue by Slither88** [joshiejack/Harvest-Moon#16]
Something with the loot table crashes when I quit and try to reload the world. I am in the mining hill on the second floor when I quit. Only did it once though and only when saving and quitting and reloading the map not when loading a map from run.

Crash log:
http://pastebin.com/iy2zm2dE

**Comment by Slither88** [comment]
Seems to be happening when you enter a new dimension. Just came out of the mine with an escape rope and it crashed again with seemingly the same data after quitting and reloading the world.

Crash log:
http://pastebin.com/tBgFfMdH

**Comment by Slither88** [comment]
Oh and it crashes in the sense of generating a crash log but the instance of Minecraft needs to be manually closed with task manager or MultiMc Kill. Playing in SSP. With build: Harvest-Festival-1.10.2-0.5.0-41

**Comment by joshiejack** [comment]
Thanks. I'll take a look tonight. What did I break now =P

**Comment by joshiejack** [comment]
Or at least I think that should do it

**Comment by Slither88** [comment]
I will test some more and let you know.

**Comment by Slither88** [comment]
All sorted now!
