### ISSUE TITLE
1000 Item Shipped Achievements not activating

### ISSUE THREAD

**Issue by Scorpinox** [joshiejack/Harvest-Moon#162]
Are the 1000 item shipped in a season achievements implemented yet? If so, I believe I found a bug. I shipped easily 2000 items, and certainly more than 1000 items over the Spring of Year 2, but did not see any achievement or other message pop up. I did not see if the new seeds were available for sale. This is using harvest festival 0.6.0-218, in the Farming Valley modpack (with modtweaker scrips changed to work with 0.6.0 of harvest festival).

**Comment by joshiejack** [comment]
They are working. You have to chat with Jenni to unlock them. (Sometimes twice).

**Comment by Scorpinox** [comment]
She said that melons (and something else?) was unlocked, but it didn't trigger the achievement (and she didn't mention cabbages). Is that the correct message?

**Comment by joshiejack** [comment]
Then you unlocked those crops. You'd need to talk to her again.

**Comment by Scorpinox** [comment]
Do I have to be in the same season as I got the thousand in to see this?
EDIT: To be clear, I talked to her many times, both while the shop is open and closed.

**Comment by joshiejack** [comment]
Yes of course. The crops aren't going to be unlocked unless it's that season.

**Comment by Scorpinox** [comment]
Ok then. I'll see if they appear in the next year. Thanks!

**Comment by Scorpinox** [comment]
Sorry to respond so late, but everything is working now. I might suggest that you make it so that the achievement triggers when you harvest 1000 crops rather than when you talk to Jenni, but that is just a suggestion.
