### ISSUE TITLE
How do you go mining?

### ISSUE THREAD

**Issue by PrinceOfIonia** [joshiejack/Harvest-Moon#165]
Sorry, I know this is a stupid question, and I'm not even sure if mining is out yet but, if it is, then how? I have the latest version of the mod. Thanks!

**Comment by GirafiStudios** [comment]
You need to unlock the Mining Hut, which allows you to enter the Mining dimension.
Github is for reporting bugs with the mod. Another time, please use Discord for these kinds of questions! :)
Invite link to Harvest Festivals discord: https://discord.gg/MRZAyze
