### ISSUE TITLE
Mine levels

### ISSUE THREAD

**Issue by jeridan** [joshiejack/Harvest-Moon#166]
Modpack: Farming Valley version 0.7.7
Harvest Festival version 1.10.2-0.5.27

I have made it to level 4 of the mine but at Y-187 there is nowhere to continue on.  Also have only found up to gold at this point.  Is there anything else beyond this?

**Comment by Andvee** [comment]
I have had this happen to sometimes (2 different worlds) the mine doesn't spawn a way to the lower level. I've made it one of the cheating exceptions where I'm allowed to use creative in my survival world. It seems to be a bug in the random generation for the mines. use creative and break 3 blocks down and if there's no room patch the hole and try another spot there are rooms under it but I can't find anyway to fix it without cheating.

**Comment by Slither88** [comment]
Since the mine is a dimension would it not work to just delete the DIM folder for that dimension and just enter the mines again? The mine resets everyday as far as I know so deleting and re-entering the dimension should not affect your gameplay too much.

**Comment by Andvee** [comment]
I don't believe it would work the mining dimension seems to always generate the same for your seed. I had a testing world and survival world with the same seed and got identical mining dimensions even if I placed the hill at a different location. Essentially to get a different mining dimension means a new world along with it.

**Comment by Slither88** [comment]
Oh yes I forgot that dimensions are based on the seed.

**Comment by joshiejack** [comment]
I changed the generation in 0.6. So hopefully this will be fixed in the future. For now you'd have to cheat and make a hole in the floor.
