### ISSUE TITLE
[Suggestion] regarding tools

### ISSUE THREAD

**Issue by Andvee** [joshiejack/Harvest-Moon#168]
I'd suggest adding a shovel tool, and adding enchantability to tools.

The only vanilla tools missing from the list are shovel and sword, and while I see the merit in discounting a sword in a mostly peaceful type mod I would like a shovel that sticks around and is easily repaired.

I'd also suggest making tools enchantable (even allowing them to be disenchanted on upgrade if it's a pain to keep enchants through upgrades). I like the tools as a convenient alternative to things such as tinkers construct but would like to customize them a bit such as adding unbreaking to my tools. I could understand you must have left it out for some reason not immediately obvious to me such as mend making repairs moot or some such, so I understand if you don't wanna add this function.

**Comment by MartinKitten** [comment]
What's about adding new enchanting system with Priest npc?

**Comment by GirafiStudios** [comment]
Thanks for your suggestions!
Enchantability is out of scope for this mod, for some of the reasons that you actually mention yourself.
As for shovels, they wouldn't actually have any practical use in the mod.
