### ISSUE TITLE
Basket Controls

### ISSUE THREAD

**Issue by Yulife** [joshiejack/Harvest-Moon#169]
Right now you rightclick to lay down your basket which is not good since you rightclick really often with an empty hand in normal gameplay. It should change to shift-rightclick, just like picking it up. Accessing it could be a custom keybind or even more cool, you look up and rightclick it. Accessing it in world would just be rightclick.

**Comment by GirafiStudios** [comment]
It is working as intended.
Interacting with any tile entity won't place it back down. Same with placing blocks - won't trigger the shipping basket to be placed either :)
