### ISSUE TITLE
Carpenter Getting Stuck, Building the General Store.

### ISSUE THREAD

**Issue by Slither88** [joshiejack/Harvest-Moon#17]
The carpenter seems to be having difficulty building the General store. I have place the blueprint on a flat area, but the carpenter keeps teleporting into the ground (I can hear him taking damage). This is with build: Harvest-Festival-1.10.2-0.5.0-74. This is what I tried so far with no luck (on SSP and Dedicated server):
- Tried waiting to see if anything gets built. Three days with him being stuck in the ground.
- Tried waiting for sun to set and sleeping. He stays stuck in the ground.
- Tried bailing him out and then sleeping. Sometimes he goes home and comes back, but then just gets stuck in the ground again.
- Tried just placing a new Yulif in creative. Both proceed to get stuck.
- If you get him "unstuck" he stays halfway into the ground and does nothing.

**Comment by Slither88** [comment]
Looks like he is doing something now. Seems it is just the sort of basement that he keeps struggling with. Maybe because he keeps trying to be a certain amount of blocks away from where he is building?

Edit: It is the basement that he keeps getting stuck with. Once that is built it all runs smoothly again.

**Comment by joshiejack** [comment]
Yeah. He never used to check distance, but I changed it, guess, I either need to increase the distance or make him entirely immune to suffocation, maybe distance should increase if building any of the blocks < the y offset. (undeground ones only). Was gonna test this today! Guess he does fail xD.

**Comment by Slither88** [comment]
Lol! Guess so. I like the increase if blocks are underground idea. The other option would also make him appear not to be doing anything and might cause panic when he just disappears.
