### ISSUE TITLE
comunial pot

### ISSUE THREAD

**Issue by goldengamer1314** [joshiejack/Harvest-Moon#170]
their is no comunial pot when they tell me to put stuff into the comunial pot i cant because there isnt one so could u please fix this

**Comment by Andvee** [comment]
Only the cow festival has been finished. Others are just there but aren't finished so they don't work as intended yet.

**Comment by goldengamer1314** [comment]
but the sheep festival works

**Comment by Andvee** [comment]
Not tried the sheep festival I posted a similar issue before and they said it's WIP and not finished.

**Comment by GirafiStudios** [comment]
Andvee is indeed correct. It is not quite finished yet, which is also why the 0.6.x builds is marked as alpha.
