### ISSUE TITLE
Issue with Harvest Festival priest

### ISSUE THREAD

**Issue by Phizzhead** [joshiejack/Harvest-Moon#172]
[crash-2017-06-12_14.47.14-client.txt](https://github.com/PenguinSquad/Harvest-Festival/files/1069342/crash-2017-06-12_14.47.14-client.txt)

Crash report link: https://gist.github.com/Phizzhead/b030ee6da61411993628116929ed1f86

**Comment by GirafiStudios** [comment]
Thanks for the report!
The code that is crashing does not even exist in the latest version of Harvest Festival, which is version 0.6.0-218. If you can reproduce the issue with that version, please open another issue about it then :)
