### ISSUE TITLE
Crash when trying to plant on BOP dirt

### ISSUE THREAD

**Issue by DcNdrew** [joshiejack/Harvest-Moon#173]
https://pastebin.com/3Mq730tK

**Comment by GirafiStudios** [comment]
Thanks for you report!

**Comment by GirafiStudios** [comment]
Thanks for your report!
This is not reproducible with just Biomes O' Plenty and Harvest Festival on latest versions.
It could look like that you are using some sort of "Fake Player" to attempt to plant the seeds. I added in a check to make sure seeds are not attempted planted on air (Which is the cause of this crash)
