### ISSUE TITLE
Certain mods being present causes all shops to be closed at all times.

### ISSUE THREAD

**Issue by BionicFelps** [joshiejack/Harvest-Moon#175]
Harvest-Festival-1.10.2-0.6.0-218

Seen with Ex Nihilo Adscensio, and Galacticraft.

I did have a log here, but I realized that log was not one where the issue was present, I'll have a log shortly...

This happens even when shops always open is set to on.  In some cases I've been able to shop at the cafe, however, all items say that they are corrupted (that's Ex Nihilo Adscensio)

**Comment by GirafiStudios** [comment]
Thanks for your report!
I have no idea where to get Galacticraft from for 1.10.2, and I was not able to reproduce this with Ex Nihilo Adscensio. Please open a new issue with more information, if you are still able to reproduce this yourself :)
