### ISSUE TITLE
[Question] This is about the CraftTweaker integration for integrating crops

### ISSUE THREAD

**Issue by GazbonicAcid** [joshiejack/Harvest-Moon#176]
According to [External Tweaker](https://minecraft.curseforge.com/projects/external-tweaker/)'s external crafttweaker script editor,
Harvest Festival has CraftTweaker integeration for adding other mods' crops to Harvest Festival.
Can you please confirm whether or not this integration is fully implemented?
And if it is, I would like to see some proper documentation for it.
Or at least for you to explain how to use it to me here.

**Comment by LeDemmers** [comment]
Documentation is out there, it also somewhat outdated. However we will be releasing a more official documentation on it.

**Comment by GirafiStudios** [comment]
I just finished updating the documentation for Harvest Festivals MineTweaker support on MineTweakers wiki.
You can find it here: http://minetweaker3.powerofbytes.com/wiki/Mods:Harvest_Festival_Support
