### ISSUE TITLE
Yulif not working if not within 5 block range

### ISSUE THREAD

**Issue by Boordfles** [joshiejack/Harvest-Moon#177]
I'm having issues with Yulif not working if I'm not in a 5 block radius. 
Is this what you need?
[Latest Log](https://gist.github.com/Eviechu/a3533d7b8f1a64efb2ff37f023c8393f)
I can place buildings down correctly, but unless I am right next to Yulif he just stops doing anything.

I'm using Minecraft Version 1.10.2, and Forge 2316. This is a custom modpack that my brother and I created. I'm pretty sure there's a mod interfering with Yulif, but I'm not sure how to check which one is doing it.

Please let me know if that's not the right log or if you need any more information.

**Comment by Boordfles** [comment]
Update: After loading up Minecraft this morning, he seems to be working somewhat. I can walk away from him now, it's just that he's a little slower than he normally is.

**Comment by Boordfles** [comment]
Update 2: I sent Yulif to go build the Mining Hill and he disappeared for five minutes, only to reappear with a dupe of himself. They are now both working on it. What is even happening.

**Comment by Boordfles** [comment]
![2017-06-30_13 51 52](https://user-images.githubusercontent.com/29764150/27747945-7584c57c-5d9b-11e7-9694-46909271b4a9.png)

**Comment by GirafiStudios** [comment]
Thanks for your report!
You are using a old version of HF. This should be fixed in newer versions.
Please try out Harvest Festival version 0.6.0-218 from CurseForge. If you can reproduce it with that, please open another issue about it :)
