### ISSUE TITLE
Crash after carpenter finishes building Carpenter's house.

### ISSUE THREAD

**Issue by MoxieGrrl** [joshiejack/Harvest-Moon#18]
He finishes the build and then I crash to desktop with the following:

http://paste.feed-the-beast.com/view/f952ab28

Continues crashing on reloading the world.

**Comment by gilfort** [comment]
My game just froze upon reloading the world, the log of this is here
http://pastebin.com/HmDJCeuN
seems like Yulif has fallen down a block and is now ticking.

**Comment by GirafiStudios** [comment]
@gilfort , your game didn't freeze, it crashed (Which it also says in your log there).
It is the same crash as MoxieGrrl reported (I guess that is why you reported it here?)
Joshiejack will look into this as soon as he is home.

**Comment by gilfort** [comment]
Yeah, you're right. What i meant was, that the game didn't forceclosed this time. 
I just tested it again, and this time the crash came a good few minutes after he finished the building. Just in case its important
