### ISSUE TITLE
yulif spawning every time place new building

### ISSUE THREAD

**Issue by auspexx** [joshiejack/Harvest-Moon#180]
I am playing on a server for your mod and every time we place new building of the starting 3 it spawns a new yulif I will attach the screenshots. is there a known fix so I can pass onto the server providers?
its version 0.5.27 its version 0.8.0 of farming valley 
I have placed all buildings available in the screenshot but still wont remove it from the list of buyable blueprints
![2017-07-30_23 52 35](https://user-images.githubusercontent.com/30579798/28757800-c14472b0-7582-11e7-968d-c1fed43b0453.png)
![2017-07-30_23 52 43](https://user-images.githubusercontent.com/30579798/28757801-c5ad449e-7582-11e7-85db-f63899f74de4.png)
![2017-07-30_23 53 35](https://user-images.githubusercontent.com/30579798/28757802-c7442dc2-7582-11e7-894b-15c838088564.png)

**Comment by alicheek** [comment]
Seems like something to do with the data file not saving what that player has already placed meaning they cant go to the next building schematic as the game thinks they have not built the last buildings that are requirements.

**Comment by GirafiStudios** [comment]
Thanks for the report!
This issue was fixed a good while back, as part of the 0.6.0 update :)

**Comment by ToxicVxuro** [comment]
This issue was fixed but yet I'm having the exact same thing can someone help me?

**Comment by SirKaplan** [comment]
Yep still happened to me I got 4 Yulifs...
