### ISSUE TITLE
Vivecraft and HarvestFestival

### ISSUE THREAD

**Issue by Raizerker** [joshiejack/Harvest-Moon#181]
Minecraft crashes when running HarvestFestival on Vivecraft.

Mods installed are:
Harvest Festival
ViveCraft
OptiFine
Mercurial

[crash-2017-08-24_12.16.34-client.txt](https://github.com/PenguinSquad/Harvest-Festival/files/1249570/crash-2017-08-24_12.16.34-client.txt)

**Comment by GirafiStudios** [comment]
Does this happen without Optifine?

**Comment by Raizerker** [comment]
ViveCraft can't be run without Optifine.

**Comment by Raizerker** [comment]
The creator of Vivecraft has fixed the issue.
