### ISSUE TITLE
Issue: FTB Farming Valley ver 1.10.2

### ISSUE THREAD

**Issue by SgtLeo** [joshiejack/Harvest-Moon#182]
I got a server running Farming Valley ver 1.10.2 and the season is not changing like it should, what can I do to fix it? it is not showing and errors or crash reports...  

https://gist.github.com/SgtLeo/fbe4fe74c8a0a1dec6c5839aaaf17e1b (is the fml-server-lastest.log)

Thank you for reporting!
---

 * Please upload your crash reports or logs to https://gist.github.com or similiar sites, don't just paste it in raw!
 * If the issue is not a crash, please provide your fml-client-latest.log or fml-server-latest.log
 * Before reporting your issue, please make sure it have not already been reported.
 * Make sure you have the latest version of Harvest Festival, since your issue might already have been fixed!
 * Preferably provide us with what Forge version you are using. 
 * If the issue is between Harvest Festival and another mod, please inform what version of the mod you are using. Also make sure the other mod is updated to latest version.
 * Please check out https://github.com/PenguinSquad/Harvest-Festival/blob/1.10.2/PLANS.md, before making any suggestions!

**Comment by GirafiStudios** [comment]
Seasons are longer on servers, since they run 24/7. You can change it in the config.

**Comment by SgtLeo** [comment]
If I wanted to shorting the seasons which lines or line do I use? (got a feeling it is the 1st listed below)
I:"Dedicated Server > Days per season"=365
I:"Integrated Server > Days per season"=30
