### ISSUE TITLE
[Question] Translation

### ISSUE THREAD

**Issue by siayatezerg** [joshiejack/Harvest-Moon#183]
I Have Tried Translation For zh_TW, But I don't know how to let every one can use it?
I mean where can I  uupload this zh_TW.lang

**Comment by GirafiStudios** [comment]
You can open a pull request.

**Comment by siayatezerg** [comment]
Thank

**Comment by siayatezerg** [comment]
Sorry,But I still Don't Know how to .... upload.
i almost translation of 1.10.2-0.6.0 - 218 ,but some of recipe still English. :)

please help me.

**Comment by LeDemmers** [comment]
Give us a download link for it then.

**Comment by GirafiStudios** [comment]
He had a link download link in his PR, added it manually in https://github.com/PenguinSquad/Harvest-Festival/commit/72d1d723ac0426959271b918af3591aaeaadbff5
