### ISSUE TITLE
Speech of NPC not appearing

### ISSUE THREAD

**Issue by hello-elly** [joshiejack/Harvest-Moon#187]
Hi I've started playing Harvest Festival, however the speech of the goddess stopped working, I can't see what she's saying. 

forge 1.10.2-12.18.3.2281
Harvest Festival - 1.10.2-0.6.0-218

![screen shot 2017-09-26 at 5 20 28 pm](https://user-images.githubusercontent.com/32291229/30847382-b2c6ff62-a2de-11e7-98b5-493d46197c27.png)

Thank you for reporting!
---

 * Please upload your crash reports or logs to https://gist.github.com or similiar sites, don't just paste it in raw!
 * If the issue is not a crash, please provide your fml-client-latest.log or fml-server-latest.log
 * Before reporting your issue, please make sure it have not already been reported.
 * Make sure you have the latest version of Harvest Festival, since your issue might already have been fixed!
 * Preferably provide us with what Forge version you are using. 
 * If the issue is between Harvest Festival and another mod, please inform what version of the mod you are using. Also make sure the other mod is updated to latest version.
 * Please check out https://github.com/PenguinSquad/Harvest-Festival/blob/1.10.2/PLANS.md, before making any suggestions!

**Comment by GirafiStudios** [comment]
Are you using Optifine, and perhaps a resourcepack too?

**Comment by hello-elly** [comment]
No I'm not using Optifine and I have removed the resourcepack but it's still blank

**Comment by LeDemmers** [comment]
What language are you using?

**Comment by GirafiStudios** [comment]
Also would you happen to be playing the modpack "Farming Valley"?
If that is the case, it might be related to this issue: https://github.com/PenguinSquad/Harvest-Festival/issues/150

**Comment by LeDemmers** [comment]
Seems you have a mod that modifies the HUD, as per your health is near the seasons bar, and your exp bar seems to be gone as well. Try removing that mod, see if that fixes it.

**Comment by hello-elly** [comment]
@LeDemmers I am using English US, and I removed that mod but it doesn't fix it, the exp car is gone because I was in creative mode

@GirafiStudios No I'm not playing the modpack "Farming Valley"

**Comment by GirafiStudios** [comment]
Closing this, since the issue have already been raised in https://github.com/PenguinSquad/Harvest-Festival/issues/150

**Comment by GirafiStudios** [comment]
Would you happen to be using a OS, that is not Windows?
