### ISSUE TITLE
Progress gone

### ISSUE THREAD

**Issue by key-peele** [joshiejack/Harvest-Moon#190]
I lose my progress everytime I load the game. Gold's gone and quest starts from the beginning again. But the buildings and crops is still there. Overall this mod is freaking great but the bug is keeping me from playing mod.

**Comment by GirafiStudios** [comment]
Thanks for your report!
You have to give us some more information than that. For example what Harvest Festival version etc.? Everything you think would be relevant.

**Comment by key-peele** [comment]
from version 1.10.2-0.6.0-210 to 1.10.2-0.6.0-218.

**Comment by GirafiStudios** [comment]
Alright, that's a start.
What operative system are you using?
Also would you happen to be logging in to Minecraft in offline-mode somehow?

**Comment by key-peele** [comment]
I'm using Windows 10 and yes I logging in to mc offline mode

**Comment by GirafiStudios** [comment]
That is your problem then. We don't support fake Minecraft accounts.
