### ISSUE TITLE
[Suggestion] Nest boxes and hoppers

### ISSUE THREAD

**Issue by Andvee** [joshiejack/Harvest-Moon#191]
I'd suggest allowing nest boxes to empty contents into hoppers. Currently it seems nest boxes require a player to right click them to collect eggs. Considering crops are the main focus a majority of the time it's quite easy too forget emptying nest boxes.

**Comment by GirafiStudios** [comment]
Thanks for your suggestion!
That is exactly the way it's meant to work. It is meant to be done manual, and automation is - and never will be the focus of Harvest Festival.
Appreciate the feedback though :)
