### ISSUE TITLE
fish hook entity causing dedicated server crash on login attempt 

### ISSUE THREAD

**Issue by Cernunnas** [joshiejack/Harvest-Moon#192]
After playing for a few days without any issues, my dedicated server suddenly started crashing everytime I tried to login from my client. Checking the error logs it seems the culprit was a fish hook entity. I enabled Forge's start up option to automatically remove crashing-causing entities. This allowed me to log into the game. Everything seemed normal, except the fisherman was no longer selling fishing hooks.

My Forge version is 1.10.2-12.18.3.2511-universal. Find the crash report here: 

https://gist.github.com/Cernunnas/0a99db4e4e54b555560bbf02a5a3aee1

**Comment by GirafiStudios** [comment]
What exact version of Harvest Festival are you using?

**Comment by Cernunnas** [comment]
It's 0.6.0 for 1.10.2.

**Comment by GirafiStudios** [comment]
Just pushed a commit that should fix the issue.
Please go try out the latest Jenkins build, and see if it fixes it for you!
Link: http://girafi.dk/jenkins/job/Harvest%20Festival/job/Harvest%20Festival%200.6.X%201.10.2/
