### ISSUE TITLE
NPCs not behaving properly

### ISSUE THREAD

**Issue by Andvee** [joshiejack/Harvest-Moon#193]
using HF 0.6.0-7

When using Carpenter's blueprint to construct building Yulif will sometimes despawn, and stop constructing his home.

Yulif no longer returns to his home after constructing a building (or wander around at all), and spawns a duplicate of himself. If killed after this he will not respawn naturally. Buildings constructed so far where he exhibits this behavior is mining hill, and blacksmith.

**Comment by GirafiStudios** [comment]
Conversation continued on Discord.
Might be some mod conflict causing the issue.
