### ISSUE TITLE
Question For The Team

### ISSUE THREAD

**Issue by Boolyman** [joshiejack/Harvest-Moon#194]
I would have sent a message through Curse, but I did not know which member of the team would be the one(s) to talk to.  I am looking for an economy based shopkeeper and village mod for my upcoming pack.  It will be a sequel to my most popular pack, so I am hoping to make it much more in depth.

Long story short, is there any possibility this will be getting a 1.12.2 upgrade?  Also, is the NPC dialogue configurable?

**Comment by GirafiStudios** [comment]
1.12.2 is planned in the future, but it is gonna take a while still. Minecraft 1.13 will probably be out by the time we start porting, so we might just go straight for 1.13 - depends on what the community is using at the time really.
The NPC dialogue is not really configurable no, although I guess you could change it in the localization file if you really wanted to.
Hoped that answered your questions :)
Although another time, please ask your questions on Harvest Festivals Discord instead (Invite link: https://discord.gg/MRZAyze )
