### ISSUE TITLE
Minor issue with number of items bought mouseover

### ISSUE THREAD

**Issue by Andvee** [joshiejack/Harvest-Moon#196]
using HF 0.6.0-7

Buying multiples of items such as seeds shows how many have been bought but it doesn't change the number for different items. After buying 7 beetroot, carrot, and spinach seeds it said I had bought 21 beetroot seeds.

![image](https://user-images.githubusercontent.com/8715158/33569363-3c0fe97a-d8de-11e7-91b3-2fa6673e8406.png)

**Comment by GirafiStudios** [comment]
Unable to reproduce. Conversation continuing on Discord.
