### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by joshiejack** [joshiejack/Harvest-Moon#197]
Thank you for reporting!
---

 * Please upload your crash reports or logs to https://gist.github.com or similiar sites, don't just paste it in raw!
 * If the issue is not a crash, please provide your fml-client-latest.log or fml-server-latest.log
 * Before reporting your issue, please make sure it have not already been reported.
 * Make sure you have the latest version of Harvest Festival, since your issue might already have been fixed!
 * Preferably provide us with what Forge version you are using. 
 * If the issue is between Harvest Festival and another mod, please inform what version of the mod you are using. Also make sure the other mod is updated to latest version.
 * Please check out https://github.com/PenguinSquad/Harvest-Festival/blob/1.10.2/PLANS.md, before making any suggestions!

~Just to cause an issue

**Comment by GirafiStudios** [comment]
Fake issue detected. Automatic closing of issue will be executed shortly.
