### ISSUE TITLE
Chicken Not Laying Eggs

### ISSUE THREAD

**Issue by MuirDH** [joshiejack/Harvest-Moon#198]
I have noticed that my chicken doesn't always lay eggs. It will lay them for a few days, but then all of a sudden stop for weeks at a time. Just when I'm about to buy a new one, it starts laying them again. 

I keep the feeding tray full and am giving it a chicken treat nearly every day as well. It isn't ill, as far as I can tell (there are no ill swirls coming from it). I'm using the poultry hut as the farm. I've built a small pen behind it and the chicken can go inside the hut or outside into the pen as it wishes. the feeding tray is in the corner by the main entrance and the nesting box is in the opposite corner in the back of the hut near the pen entrances. 

I'm playing with the Farming Valley modpack, V 0.9.1 which uses Harvest Festival V 1.10.2-0.5.27

**Comment by Student-HXJ** [comment]
I have the same problem, I think the problem may be the height of where the coop placed,because I placed the coop on the floor then I get eggs everyday.

**Comment by MuirDH** [comment]
When you say "the floor", JA-venger, do you mean at ground level? I'll have a play around later and see if I can raise the ground up a bit in that area so that the barn is completely on the ground. Currently the floor is raised like half a block above the dirt blocks underneath it, which is how it was built in the game. 

Once I've experimented a bit, I will post here to let everyone know what the results were.

**Comment by Student-HXJ** [comment]
I just place coop on the ground level, but I think the point is the height. chicken coop+egg=2 > 1.5, so chicken didn't lay eggs always，I'm just guessing，because when I have more than two chicken, the chicken began to lay eggs but not everyday.

**Comment by GirafiStudios** [comment]
Thanks for your report!
They are only laying eggs if they are healthy. So make sure you feed them, and try giving them some medicine.

**Comment by MuirDH** [comment]
After playing around with this over the weekend, here is what I've done and what I've found:

What I did:
 * Removed the floor of the chicken barn and replaced it with dirt blocks, making sure that there were dirt blocks at least two blocks deep underneath that (so three dirt block layers - the floor and two underneath). 
* Placed two nesting boxes. One inside the barn on the dirt floor, the other outside the barn (one layer down lower than the barn floor) on the ground. 
* Each in game day, I made sure that the feed boxes were full, fed the chicken a treat, and picked it up and threw it down as well. I also tried giving it medicine every other day in case it was ill (It never took the medicine)
Result: No eggs in either box for the entire duration (14 in game days). 

What I Did, Part 2:
* Took one of the eggs I had kept from when I first got the chicken, put it in the incubator, waited for it to hatch and for the chick to grow up. 
* While it was growing up, I did everything that was doing for the adult (original) chicken as detailed above.
Result: No eggs from the original chicken while the new baby chick was growing up. However, as soon as the baby chick grew up, I started getting both small and large eggs (one each per day). 

Another 14 in game days later and I'm still getting eggs from both chickens.  This leads me to believe that there must be a bug in play here. Something that results in a single chicken not laying eggs until you get additional chickens. Maybe they get lonely? Who knows lol.

**Comment by GirafiStudios** [comment]
Tried updating to 0.6.x?

**Comment by MuirDH** [comment]
I now have four chickens and am getting 4 eggs per day, as I'm meant to. 

Unfortunately, your mod is part of a modpack (Farm Valley) and Keehan (the maker of the pack) hasn't updated your mod to 0.6.x yet. Hopefully he'll do so soon. I've read your release notes and am really looking forward to some of the things in there!

This is a great mod, by the way. I'm really enjoying it.
