### ISSUE TITLE
NPC disappeared 

### ISSUE THREAD

**Issue by Funtemmie** [joshiejack/Harvest-Moon#199]
So the issue is that the carpenter isn't at his house. I've built it and talked to him before but now he's not there. I've slept a couple of days and waited but he's not there. Jade is still there though. Help?

**Comment by GirafiStudios** [comment]
Thanks for your report!
It sounds like you are using 0.5.x, most likely playing Farming Valley I assume?
This should be fixed in 0.6.x :)

**Comment by Funtemmie** [comment]
um this is just harvest festival

**Comment by Funtemmie** [comment]
oh and some other mods
