### ISSUE TITLE
Strange Problem...Massive Ocelot Spawn?

### ISSUE THREAD

**Issue by Darianna77** [joshiejack/Harvest-Moon#201]
Okay....i have tried again to play with my Moondew Vallay Pack (little bit self updatet because of owner not active anymore) and have strange issues with ocelots..
When i come to a jungle like biome...or an sacred spring biome too...massive amounts of ocelots are spawning.
Have tried out now several hours whats can cause this bug....have made a new instance in twitch...only with rtg...biomes o plenty, jouneymap and jei ( i would try the same world generation because i thought its maybe one of this mods...)...all okay in the sacred springs....only 2 ocelots or so...
then i have added harvest festival....bäämmmm 50 ocelots or so...

i dont know whats wrong...but the bug must be something to do with harvest festival...i dont know if its old...or no

maybe anyone else have seen this?

The Problem does not appear in the latest 05 Version... in the last two Versions from 0.6 it does. Dont know what is with Versions before...have only testet the 05er and the two last 06er

**Comment by GirafiStudios** [comment]
Was resolved after conversation on Discord.
