### ISSUE TITLE
[Bug] Yulif not actually building anything when he is supposed to.

### ISSUE THREAD

**Issue by MainFreak** [joshiejack/Harvest-Moon#205]
Hello,
I am not sure if this bug is caused by Harvest Festival itself, but it seems like Yulif is not actually building anything when he should. I discovered that bug while testing "Renaissance" on a server hosted by someone else, so I can not provide logs as of right now, and probably no accurate ones when I am able to.
I assume that this bug may be related to Sponge as the Server Owner insists on using Plugins and Sponge in general, I have not experienced this bug in singleplayer or multiplayer without Sponge/Plugins either. Basically this was the result:
![2018-03-08_02 41 45](https://user-images.githubusercontent.com/20734190/37128906-a4ee8b4e-227c-11e8-90af-fea00e0911d9.png)

**Comment by MainFreak** [comment]
If inaccurate logs are still alright I will ask the owner for them later.

**Comment by GirafiStudios** [comment]
Thanks for your report!
Unfortunately Harvest Festival does not support Sponge. If you can reproduce this with just Harvest Festival and Forge, please open a new issue.

**Comment by MainFreak** [comment]
Apparently the bug is not caused by Sponge directly, but by a plugin that restricts block placement (some "claim land" plugin). I will try reproducing it with a forge mod if that will make it a valid issue.
