### ISSUE TITLE
Upgraded tool vanishing from inventory

### ISSUE THREAD

**Issue by Concolora** [joshiejack/Harvest-Moon#206]
So, this just happened to me in singleplayer (though opened to LAN with one other player). The upgraded tool appeared in the first slot of my hotbar (replacing a diamond pick) and also the first empty slot of the hotbar. When I tried to move the upgraded tool (copper watering can), both vanished and the pick reappeared.

MC:1.10.2
Forge: .2511
Harvest Festival: 0.5.27
Modpack: Farming Valley 0.9.1

**Comment by GirafiStudios** [comment]
This is fixed in HF 0.6+
