### ISSUE TITLE
Blacksmith shop functions not working

### ISSUE THREAD

**Issue by ChaosSaiyan** [joshiejack/Harvest-Moon#210]
I have the latest version of the mod and I'm using it in the Farming Valley modpack. The blacksmith worked before I updated the mod but now he just says generic chat lines and doesn't even offer the shop hours option anymore.

*Edit: Church is also having this issue.

**Comment by spykid01** [comment]
are you playing the farming valley Modpack?

**Comment by spykid01** [comment]
[ShopsItems.zip](https://github.com/PenguinSquad/Harvest-Festival/files/1959960/ShopsItems.zip)
Replace the script you have with this script and it should fix

**Comment by GirafiStudios** [comment]
There is nothing I can do about how a modpack alters stuff, so closing this now.
Very kind of @spykid01 to provide a solution though :)
