### ISSUE TITLE
How can I change the price of the crops?

### ISSUE THREAD

**Issue by 476668843** [joshiejack/Harvest-Moon#217]
I want to reduce the pirce of crops for server play.

**Comment by GirafiStudios** [comment]
http://minetweaker3.powerofbytes.com/wiki/Mods:Harvest_Festival_Support

**Comment by 476668843** [comment]
Thank you for your timely reply.
Actually，this is my first time to use it. Can you simply teach me how to do it?
For example , I just want to use "mods.harvestfestival.Crops.setValue("crop name", 20, 10);" this code to change some prices of corps, I want to know how to write and where should I put it.
Thanks a lot !

**Comment by GirafiStudios** [comment]
Read in to how CraftTweaker (Minecraft mod. You can find it on CurseForge) work :)
