### ISSUE TITLE
Flowerpot in Jade's 2nd floor causes her to suffocate

### ISSUE THREAD

**Issue by purpleposeidon** [joshiejack/Harvest-Moon#24]
Or something.

**Comment by joshiejack** [comment]
I've never had her suffocate from the flower pot O.o. NPC deaths shouldn't matter too much since they'll respawn the next day. I guess I could teleport them out of danger if they get stuck in something? What do you suggest?

**Comment by purpleposeidon** [comment]
Ah, well, we were on the second floor & I somehow managed to push her onto the flower pot, which stuck her head in the roof. Maybe remove the flowerpot?

**Comment by Yulife** [comment]
What about the NPCs teleporting _whenever_ they suffocate joshie

**Comment by GirafiStudios** [comment]
This was caused by Jade spawning inside/half inside the flowerpot on the 2nd floor. After Joshie redid all the buildings her spawn point have now changed to be in the middle in front of the two "beds" :)
