### ISSUE TITLE
Carpenter should start building from ground level, not lowest Y level

### ISSUE THREAD

**Issue by purpleposeidon** [joshiejack/Harvest-Moon#25]
Otherwise he wanders around mysteriously.

**Comment by purpleposeidon** [comment]
Otherwise he wanders around mysteriously.

**Comment by joshiejack** [comment]
Surely it would be just as confusing if he's building the basement later. Perhaps instead I could get him to say, Hey blah, as you can see i'm busy building x, currently working on building the basement. At least then you at least know what's going on.

**Comment by GirafiStudios** [comment]
Added chat for the carpenter that informs the player what building he is currently building in https://github.com/PenguinSquad/Harvest-Festival/commit/b60878594975c2014abaedb9190cad21bea83c3c. Should hopefully makes it less confusing when he is wandering around in the same area :)
