### ISSUE TITLE
Jade's take-flowers-for-turnip-seeds logic is inverted

### ISSUE THREAD

**Issue by purpleposeidon** [joshiejack/Harvest-Moon#26]

**Comment by joshiejack** [comment]
Do you mean she doesn't take the flowers, or something else. There's nothing anywhere where she should take the seeds. But I see the quest wasn't set to actually take them.

**Comment by purpleposeidon** [comment]
She gave me free turnip seeds when I had 5 flowers, and when she stopped giving seeds out at day 10-ish, she took my flowers.
