### ISSUE TITLE
Causes an excessive amount of GC?

### ISSUE THREAD

**Issue by purpleposeidon** [joshiejack/Harvest-Moon#28]
My ability to investigate this is very limited unfortunately.

**Comment by joshiejack** [comment]
I reckon a lot of that was probably to do with the building render perhaps? Unless you were doing something else.

**Comment by purpleposeidon** [comment]
Nah, just kind of standing around. Maybe poke it with jvisualvm. This could also be me derping.

**Comment by GirafiStudios** [comment]
After running a GC dump in Java VisualVM for about an hour the other day and an hour today I didn't notice anything related to Harvest Festival, so closing this for now!
If anybody else experience anything similiar we will take this up again :)
