### ISSUE TITLE
Cows have transparent eyes

### ISSUE THREAD

**Issue by purpleposeidon** [joshiejack/Harvest-Moon#34]
## Thank you for reporting!
- Please upload your crash reports or logs to [gist](https://gist.github.com/) or similiar sites, don't just paste it in raw!
- If the issue is not a crash, please provide your fml-client-latest.log or fml-server-latest.log
- B̵e̶f̵o̴r̵e̷ ̸r̵e̷p̷o̷r̶t̸i̶n̷g̸ ̸y̶o̸u̵r̴ ̷i̵s̶s̸u̸e̸,̸ ̶p̵l̷e̷a̴s̴e̸ ̴m̵a̶k̴e̷ ̵s̷u̵r̷e̴ ̶i̴t̷ ̸h̶a̸v̸e̸ ̵n̷o̵t̵ ̷a̶l̴r̵e̸a̴d̷y̵ ̷b̷e̸e̸n̵ ̴r̴e̵p̴o̴r̸t̵e̴d̷.̴
  ̴ ̷_̴ ̸M̵a̴k̸e̸ ̸s̷u̷r̷e̵ ̶y̶o̸u̸ ̷h̵a̸v̴e̴ ̷t̷h̸e̵ ̷l̸a̴t̶e̷s̶t̶ ̴v̶e̵r̵s̶i̴o̸n̶ ̶o̷f̵ ̷H̶a̶r̸v̷e̵s̴t̸ ̴F̸e̶s̵t̵i̶v̷a̶l̵,̵ ̴s̸i̴n̸c̵e̵ ̶y̶o̴u̷r̵ ̴i̵s̴s̷u̷e̵ ̵m̴i̷g̸h̸t̸ ̵a̷l̵r̴e̶a̶d̷y̸ ̴h̵a̵v̴e̵ ̴b̸e̶e̷n̸ ̶f̵i̵x̷e̵d̸!̷
  ̵ ̵_̵ ̵P̷r̸e̷f̸e̸r̶a̷b̷l̵y̴ ̴p̷r̵o̶v̵i̷d̸e̵ ̶u̴s̴ ̸w̴i̸t̵h̴ ̶w̸h̴a̴t̵ ̸F̷o̶r̵g̴e̸ ̶v̵e̸r̶s̶i̸o̵n̵ ̵y̷o̷u̴ ̸a̷r̶e̵ ̵u̸s̷i̶n̷g̶.̴ ̶
  ̴ ̸_̷ ̸I̷f̵ ̴t̷h̷e̴ ̷i̵s̶s̸u̵e̸ ̶i̸s̴ ̵b̴e̴t̷w̸e̴e̶n̶ ̴H̶a̴r̴v̴e̷s̴t̸ ̵F̶e̶s̶t̴i̷v̶a̶l̵ ̸a̷n̵d̴ ̴a̶n̵o̶t̴h̷e̵r̷ ̴m̸o̷d̸,̸ ̵p̸l̸e̵a̶s̷e̷ ̷i̴n̸f̶o̸r̷m̷ ̷w̸h̴a̵t̶ ̷v̶e̴r̴s̶i̵o̴n̶ ̵o̷f̸ ̷t̴h̶e̸ ̴m̸o̸d̷ ̸y̷o̶u̷ ̴a̸r̸e̴ ̵u̸s̷i̵n̶g̸.̶ ̷A̶l̶s̵o̸ ̸m̴a̷k̶e̷ ̷s̷u̴r̸e̸ ̷t̵h̷e̴ ̵o̷t̴h̶e̵r̶ ̴m̵o̵d̶ ̷i̷s̷ ̶u̶p̸d̷a̵t̶e̵d̴ ̶t̴o̸ ̸l̵a̶t̷e̸s̶t̴ ̸v̷e̷r̴s̶i̴o̵n̸.̷
  ̷ ̸_̷ ̵P̷l̴e̵a̵s̵e̸ ̶c̶h̶e̵c̶k̸ ̸o̶u̴t̸ ̷[̴P̶l̴a̶n̷s̵.̵m̴d̷]̵(̶h̸t̵t̶p̸s̷:̴/̸/̸g̷i̷t̴h̸u̸b̶.̷c̵o̶m̴/̵P̵e̵n̸g̶u̸i̸n̸S̴q̶u̵a̵d̶/̵H̵a̷r̴v̸e̴s̴t̷-̵F̴e̸s̶t̶i̷v̵a̴l̵/̸b̶l̶o̵b̵/̵1̶.̷1̴0̵.̵2̶/̴P̸L̷A̷N̴S̶.̶m̵d̸)̸,̵ ̸b̴e̷f̷o̷r̴e̸ ̴m̴a̷k̶i̵n̵g̷ ̴a̸n̷y̵ ̵s̷u̷g̸g̷e̴s̵t̴i̵o̵n̸s̴!̸

**Comment by joshiejack** [comment]
Damn I really messed up comverting to png8 heh. I should go and check all the rextures i resaved, looks like sheep eyes are transparent too
