### ISSUE TITLE
[Compat Request] Better With Mods

### ISSUE THREAD

**Issue by squirrelkiller** [joshiejack/Harvest-Moon#38]
Better With Mods Link: (https://minecraft.curseforge.com/projects/better-with-mods)

Better With Mods adds planters and light blocks.

Planters are required to grow plants away from water (which it prevents the usual way of picking up in a bucket and placing elsewhere). Beyond that Planters work basically identically to vanilla farmland in function, they just do not require hoeing and normally act as being "hydrated" farmland. 

While lightblocks are needed to grow the hemp added by BWM underground or indoors.

My suggestion is maybe allow the use of Planters in Harvest Festival, and (as a bit of an odder option that I thought of but expect rejection for obvious reasons) allow use of Light Blocks to create "greenhouses".

**Comment by joshiejack** [comment]
Greenhouses are something that are indeed planned for the future. I guess I just forgot to put them on the plans list. Out of interest how hard are planters to get? I don't really want to obsolete the watering can from the get go. I do have sprinklers, which are a bit later game. So having auto hydration isn't an issue. Just more the timing of it.

(Not a mod I've actually played sorry, so have to ask questions xD)

**Comment by squirrelkiller** [comment]
So planters are a post nether feature, you require blaze rods and netherrack to craft one of the devices required to craft them.

Since Better With Mods is a forge remake of Better With Wolves, with also the goal of being more compatible with other mods, the Better With Wolves wiki is normally a valid resource, this is one such case:

http://sargunster.com/btw/index.php?title=Kiln

The overall resource cost of a Kiln needed to make a planter is:

12 clay
24 netherrack processed through a set of machines
A bunch of wood to craft a series of machines which varies depending on exact set up powering it.
1 string
1 blaze powder
2 redstone
A bit of stone here and there which can vary in exact amount needed depending on design and set up, but you need at least 4 for crafting.
Around 3 leather.
Some form of carefully tuned redstone clock for it to work which is design dependant in resource cost.

Then there is the cost of the turn table to make planters, which is:

5.5 planks
4 stone
4 sticks
1 clock (4 gold plus 1 redstone)

The planter itself just requires some clay on the turntable before being cooked in the kiln. Then you just put in a dirt block.

All in all I can get one Planter within 5 to 6 hours of play if that is my only focus and I am rushing that one thing. Even then I would probably take longer depending on my luck. Much longer for most players, I would say probably 12 hours of play for most people.

**Comment by joshiejack** [comment]
Ahh ok. That seems like it would take sufficient enough time/effort. I'll probably have a look in to it then.

**Comment by GirafiStudios** [comment]
Just talked to one of BetterWithMods devs about this. And changes on both BMW and our side need to be made for this to work. Since BMW does not support 1.10.2 anymore, this will have to wait until HF is moving to 1.12.2.
Added to https://github.com/PenguinSquad/Harvest-Festival/blob/1.10.2-0.6.X/PLANS_1.12.md
