### ISSUE TITLE
[Feature Request] Some creative tool to use (right click) on an NPC to disable wandering

### ISSUE THREAD

**Issue by MyNameIsKodos** [joshiejack/Harvest-Moon#41]
More often than I care to admit have I lost track of Jenni, Brandon, or Jim.  Some way of disabling their wander, so when their shops are open they are guaranteed to be in their store.  Some, I've even found in chunks that weren't even loaded because of being too far from our town.

**Comment by joshiejack** [comment]
Not really a point in this item, since they don't really wander very far anymore.
