### ISSUE TITLE
[Feature Request] Localization Improvement

### ISSUE THREAD

**Issue by GWYOG** [joshiejack/Harvest-Moon#43]
When using Harvest-Festival-1.10.2-0.5.4-83.jar on Jenkins, I found that some localization on the Calendar HUD should be improved.

Here is a screenshot of HF on curse (:P) with the calendar HUD. 
![hf](https://cloud.githubusercontent.com/assets/16167715/18963483/c1187d92-86a7-11e6-9e7b-1062cc7db475.png)

And these are my requests.
1. I'm a Chinese and here are three screenshot of _Harvest Moon: Friends of Mineral Town_, which was translated in Japanese, Chinese and English separately.
   ![default](https://cloud.githubusercontent.com/assets/16167715/18963153/52e86dce-86a6-11e6-9fa9-851d603cb3f0.jpg)
   ![default](https://cloud.githubusercontent.com/assets/16167715/18963159/553bd868-86a6-11e6-8366-dac072786a4a.png)
   ![default](https://cloud.githubusercontent.com/assets/16167715/18963160/57a4bf98-86a6-11e6-89d9-a17c7b1b25f7.png)
   As you may see, people from different countries express the date in different ways. For the people using English, they may say "Spring 1" directly. However, Chinese and Japanese may say "春1日", in which "春" means spring and "1日" means the first day. "1" makes no sense without "日" in Chinese and Japanese.
   So could you make the date on the calendar be localized as "Spring %d", etc. So we can translate them in a pleasant way for Chinese and Japanese? Thanks. (And I think these entries would be separate with the entries of the tooltips of the seeds' in en_US.lang.)
2. I found nowhere to translate the "(MON)", "(TUE)", etc. on the Calendar HUD. Could you add l18n supports for them? 

Thank you very much!

**Comment by joshiejack** [comment]
Will do!

**Comment by 3TUSK** [comment]
imo "Spring 1st" is better than "Spring 1".

**Comment by joshiejack** [comment]
Nah, that's grammar and makes it way more complicated and if i was to do
that it would be 1st Spring.
