### ISSUE TITLE
Indoor tilled farmlands should not be in a watered status on a raining day

### ISSUE THREAD

**Issue by GWYOG** [joshiejack/Harvest-Moon#44]
Just as what the title says, I think the tilled farmland which is covered by other blocks above it should not be in a watered status on a raining day like other outdoor tilled farmlands.

P.S. I'm using Harvest-Festival-1.10.2-0.5.4-83 from Jenkins

**Comment by joshiejack** [comment]
Can't believe i made this oversight...  Then again i do have all my farms
outside xD
