### ISSUE TITLE
[Documentation] ZERO documentation on the CraftTweaker integration

### ISSUE THREAD

**Issue by GazbonicAcid** [joshiejack/Harvest-Moon#47]
It says on the curse/curseforge page that HarvestFestival has CraftTweaker integration....
And yet the info needed to prove it has it, let alone to _use_ this integration, is missing.

**Comment by joshiejack** [comment]
It wasn't me who wrote that. Don't know why Yulife decided that was a feature... Yes it has it. But I changed it a little that's why I didn't document it yet. Literally planning on doing that once I get todays release uploaded.

**Comment by GazbonicAcid** [comment]
okay, thankyou.

**Comment by GazbonicAcid** [comment]
I'll probably be adding Harvest Festival to my modpack.
I'll **_definitely_** be adding it to my pack if/when this feature I requested gets implement in some way, assuming I haven't added it yet by then.
https://github.com/PenguinSquad/Harvest-Festival/issues/39

**Comment by joshiejack** [comment]
http://minetweaker3.powerofbytes.com/wiki/Mods:Harvest_Festival_Support#Shops

In 0.5.3 and below the shops one is replace Purchasable with Sellable so addSellable. 

As for that #39 suggestion. If I am to do it. It would be a VERY long time off. I'm more interested in adding content than spending time on such things. You'll have to convince Girafi or someone else to do it if you want it sooner :P.
