### ISSUE TITLE
Possible Blacksmith bug

### ISSUE THREAD

**Issue by qmike1** [joshiejack/Harvest-Moon#48]
Hello I'm playing the latest version of Harvest festival with several other mods. I had just completed building the blacksmith and started the tutorial when a blank box came up I clicked trying to get out of it or proceed and it crashed my client. I tried talking to him again several times and it crashes each time. I am using forge 1.10.2-12.18.1.2092. Thank you for your hard work. 
[crash-2016-09-30_22.44.37-client.txt](https://github.com/PenguinSquad/Harvest-Festival/files/504113/crash-2016-09-30_22.44.37-client.txt)

**Comment by joshiejack** [comment]
Alright, I know the issue. Not even related to your crash report! I'll fix it shortly, and then upload. Because too important to hold off :)

**Comment by joshiejack** [comment]
https://minecraft.curseforge.com/projects/harvest-festival/files/2333395

**Comment by qmike1** [comment]
thanks for the mod and bug fixes
