### ISSUE TITLE
Crash when talking to NPCs

### ISSUE THREAD

**Issue by a-rat-girl** [joshiejack/Harvest-Moon#49]
Forge Version: 12.18.1.2094 for 1.10.2

I've been getting this crash when talking to NPCs. The "Conversion = j" is sometimes "Conversion = 4," not really sure what it means. This particular crash happens every time I try to chat with the Blacksmith,

http://paste.feed-the-beast.com/view/17b528e7

**Comment by GirafiStudios** [comment]
Caused by same thing as https://github.com/PenguinSquad/Harvest-Festival/issues/48 (Even though it is not the same error throwed), a new version of HF will be out in a bit with a fix!

**Comment by a-rat-girl** [comment]
<3

**Comment by joshiejack** [comment]
https://minecraft.curseforge.com/projects/harvest-festival/files/2333395
