### ISSUE TITLE
balance issue sweet potatoes

### ISSUE THREAD

**Issue by qmike1** [joshiejack/Harvest-Moon#51]
I really enjoy this mod and find it great. I noticed a possible balance issue with sweet potatoes. You can buy sweet potatoes for 300 gold and if you sell all 9 from the seed pack you get 1080. After the initial 6 days it seems you can harvest every other days after possibly indefinitely(i'm only on fall 15th). If I did my math right you can harvest about 12 times making for a profit of 12960 gold from a 300 gold investment. If there where a way to make them harvest able only so many times, or a reduce in profit, or more days between harvesting I think there would be a better balance with the sweet potatoes. Thank you for all the work you put into the mod

**Comment by joshiejack** [comment]
I based the values of these on the actual games. So not a surprise there. Same when it comes to the actual food :P. It's this kind of feedback was looking for, since I'm no expert on balance. Will probably take all the feedback I can on this subject, before doing a balance update :).

**Comment by joshiejack** [comment]
Rebalanced the crops for next update so closing
