### ISSUE TITLE
Spring crop refuses to go away

### ISSUE THREAD

**Issue by a-rat-girl** [joshiejack/Harvest-Moon#52]
I had some strawberries planted as the season rolled over from Spring to Summer. The next day, seeing the unharvestable crops, I removed them (with a sickle) and replaced them with Corn. Later, when I slept, and returned to the farm, the strawberries had returned, replacing the corn that was there the day before. I removed and replaced them again, but they came back again the next day. I tried removing the tilled ground beneath them, and replacing them with dirt, but they still came back.

This was printed whenever I slept (a number of times, I think one for each crop): http://paste.feed-the-beast.com/view/afbe0fd2

Exiting minecraft and re-entering the world fixed the problem, I've since cheated myself some Corn seeds to make up for the loss.

**Comment by joshiejack** [comment]
I saw this once, but it never seemed very consistent. And I haven't had it since. Can I see the full log? I'll try and recreate it in the mean time..

**Comment by a-rat-girl** [comment]
Sorry, it looks like it's split into two. The one has the forge stuff and the other has the error and stuff.
fml-client-3.log: http://paste.feed-the-beast.com/view/532994f0
2016-10-01-7.log: http://paste.feed-the-beast.com/view/53688ee4

**Comment by joshiejack** [comment]
As I was unable to recreate this based on the same things you did, All I can think of is somehow, the data wasn't remove the daily ticking. I'll explicitly remove them when I kill crops. Instead of relying on the destruction of the tile to do that.

**Comment by joshiejack** [comment]
As I was unable to recreate the issue. I tried somethings. Don't know if they'll work or not... But if you can try out this build and let me know, that would be very helpful. Part of the issue may have been that I messed up and had withered crops as growing still, as well as not removing them from the daily ticking when they did. But relying on the tile changes for that.

http://joshiejack.uk:8080/job/Harvest-Festival/job/1.10.2/87/

**Comment by a-rat-girl** [comment]
I was able to do it again when my Corn transitioned from Summer to Fall, but it didn't print anything to the log that time.

I don't know if this build fixed anything, as it produced a new crash when I loaded into a world: http://paste.feed-the-beast.com/view/a9e7b606

I was able to create a new world just fine, but planting any seeds caused the crash to occur again.

**Comment by joshiejack** [comment]
Ehhhhh annoying. What did I break. Worked in dev (but also just tried out of dev, was broken for me too). So investigates.

**Comment by joshiejack** [comment]
Okay I am going to bed now. Give this one a go when it's done building: http://joshiejack.uk:8080/job/Harvest-Festival/job/1.10.2/88/

**Comment by a-rat-girl** [comment]
This looks like it fixed it!
