### ISSUE TITLE
[Compat Issue] Crash between Harvest Festival and HoloInventory

### ISSUE THREAD

**Issue by DragooKnight** [joshiejack/Harvest-Moon#55]
Forge 12.18.1.2094
HoloInventory-1.9.4-2.0.3.138.jar
[fml-client-latest.zip](https://github.com/PenguinSquad/Harvest-Festival/files/504912/fml-client-latest.zip)

Crash to Main Menu between HoloInventory and Harvest Festival when looking at the shipment box.  Have not tested The One Probe (TOP) [have not used it, but it seems to have a inventory peek feature].

**Comment by GirafiStudios** [comment]
Thanks for reporting!
We already had this reported on Discord (Of course no way for you to know). Joshie fixed it yesterday in this commit https://github.com/PenguinSquad/Harvest-Festival/commit/4991657e433db2d47182421f95035870011e7b48 :)

**Comment by DragooKnight** [comment]
Thanks for the quick response, I await the next update with great anticipation.
