### ISSUE TITLE
some issue in multiplayer game.

### ISSUE THREAD

**Issue by nekobuild** [joshiejack/Harvest-Moon#59]
## crop texture error.
- sometimes some of nine crop from same seed look like had been ready to harvest, but actually no, and the bug crop can't be wattering, restart the server can solve this issue for a short time
## mining hill cosmetic things can be take to overworld.
- when you sleep in mining hole, it will explosion, and the cosmetic thing will drop. if someone take it to overworld, it can't be remove with any tool, I think maybe just modify blast resistance can solve this issue.
## sleep and hunger
- I'm no sure is this a bug, when multiplayer game, you can just sleep 1 second can let your hunger full, it means we never have to eat something, so maybe only sleep and skid the day can make hunger full?

**Comment by joshiejack** [comment]
Texture: If this is the released version, I believe it may be fixed in dev as I had some related issues.
Mine: Oh dear! Thought I had, guess not. Will do!
Sleep: Hmm it's meant to do it as you said. Only after sleeping. I'll take a look.

Thanks for the reports =]
