### ISSUE TITLE
[Suggestion] Image Gallery Please!

### ISSUE THREAD

**Issue by DragooKnight** [joshiejack/Harvest-Moon#61]
An image gallery of your structures from all angles inside and out. and some nice scenic shots too.  Mostly for damage repair (CREEPEEEERS! [x10 inevitability with Rough Mobs]), but also for construction ideas.  I have been (once again) inspired to build less blocky and more creatively by your structures.

**Comment by GirafiStudios** [comment]
Thanks for your suggestion!
We won't make a image gallery with all the buildings in, sorry.
But there is something easier you can do to resolve your problem. Just create a creative world and place down the building to wanna take a closer look at.  The buildings can be found in the Township creative tab :)
