### ISSUE TITLE
Torches can disable mine!

### ISSUE THREAD

**Issue by BionicFelps** [joshiejack/Harvest-Moon#65]
If you cover the floor of your mine with torches you can't enter it anymore!

I was actually trying to test to see if anything horrible happened if ore couldn't spawn, but what I stumbled upon, was if you cover the space in front of the mine entrance with torches, you will be forced back out of the mine immediately upon entering.  Presumably because the game can't find a place to put you, as all of the nearby blocks are "occupied", obviously torches shouldn't count for that though.

No sane person would ever do this, but nonetheless, feel it warranted a report.

**Comment by joshiejack** [comment]
Thanks, don't know why i decided to only look for air. Now that makes me
wonder if someone will be stupid enough to fill it up with solid blocks xD.
I guess in such a case i should just replace their blocks with air instead
of forcing you in to the wall. Of course not the case with torches where
should just allow you to spawn.
