### ISSUE TITLE
Snow after winter

### ISSUE THREAD

**Issue by BionicFelps** [joshiejack/Harvest-Moon#66]
Due to the way minecraft physics works, snow doesn't melt unless there's a nearby torch, any plans to alter this behavior in warmer seasons? Minor immersion nitpick, spose it's not really a bug, just the way minecraft works...

**Comment by GirafiStudios** [comment]
Thanks for reporting!
This is a duplicate of https://github.com/PenguinSquad/Harvest-Festival/issues/64, another time please check closed reports to see if your issue have already been reported! :)
