### ISSUE TITLE
Texture work

### ISSUE THREAD

**Issue by windikite** [joshiejack/Harvest-Moon#72]
Not sure where I should put this, but I'd like to do some texture work for you guys! I know you are planning fruit trees so if you gave me a couple ideas of what trees and fruit you would want textures for I could get started on that. Either that or if you have anything you would want me to do instead? If you don't like what I do it's np I'll just try to get better and make changes to them ;u;

**Comment by Yulife** [comment]
There's indeed a long TODO but I'm always a bit strict on getting texture help since it needs to fit the mod. Have you got any samples of textures that you've done before? :) Feel free to come in Discord

**Comment by windikite** [comment]
I'll make time to get into discord later, for now I have some sprites I made today to practice. I think I found a better program for spritemaking than sai so pardon any odd edges 
ALSO after finally getting back to finish this message I realize I have no idea how to show you what I made. 16x16 is for ants ;;

**Comment by GirafiStudios** [comment]
I will go ahead and close this, now that you are aware of the Discord :) Here is a link to make it a little easier  https://discord.gg/QHwQydC
