### ISSUE TITLE
Mod causing sky to flash on dedicated server

### ISSUE THREAD

**Issue by SgtRalphie** [joshiejack/Harvest-Moon#73]
I left my server on over night in spring but when I came back this morning it was summer and the sky was freaking out and flashing. When I remove the mod it fixes and I can't figure out how to fix it.

**Comment by joshiejack** [comment]
What other mods do you have, because this does not happen with this mod on
its own, i know shaders don't really work with it.

**Comment by SgtRalphie** [comment]
I don't have shaders or optifine. It was working perfectly before it changed seasons, and I think it might have to do with the day/night cycle being changed.

**Comment by joshiejack** [comment]
Well what mods do you have

**Comment by SgtRalphie** [comment]
actual additions
agricultural expansion
autoreglib
baby mobs
baubles
biomes o plenty
blood magic
botania
chisel
coroutil
custommobspawner
cyberware
deep resonance
mo creatures
elecCore
enderbags
endercore
ender io
expandable Backpacks
extra utils
fast leaf decay
forestry
geographicraft
goetia
guide api
harvest festival
immersiveengineering
improving minecraft
industrialcraft
inventory pets
inventory tweaks
iron chests
jei
jeibees
journeymap
JER
magneticraft
mantle
MCA
mcjtylib
mekanism(generators,tools)
minecolonies
natura
overlord
harvestcraft
platforms
possessed
psi
quark
radix core
railcraft
refined storage
roguelike
roots
RTG
shetiphiancore
tinkers
totemic
waila(harvestability,wawla)
weather 2

**Comment by joshiejack** [comment]
Only thing from looking at that list that might affect anything is weather 2. But I don't know. Wild guess. I've never heard of half of those mods, you'd just have to work out which combination of my mod and the another is doing it.

**Comment by SgtRalphie** [comment]
I tested Weather 2 and that doesn't seem to be the problem

**Comment by joshiejack** [comment]
Was literally just a guess of our two mods conflicting. Will need to try to work it out.

**Comment by joshiejack** [comment]
Have you had a chance to test yet? This isn't something I can validate myself. But honestly, this is more than likely a mod conflict, so I'll close it, especially since there has been no response.
