### ISSUE TITLE
Jade wont give seeds after getting 5 flowers

### ISSUE THREAD

**Issue by LocoMinerDad** [joshiejack/Harvest-Moon#75]
I have got the initial bag of seeds for hardy turnips and they are grown and harvested. I give Jade 5 flowers, she takes one but I dont get any seeds.

**Comment by GirafiStudios** [comment]
What version of Harvest Festival are you using?

**Comment by LocoMinerDad** [comment]
I am using harvest 5.9
I also have biomes o plenty  .2087
tough as nails .11

if that matters.

Oh and the weather isnt lining up i had snow in your spring.

 best

**Comment by GirafiStudios** [comment]
Harvest Festivals seasons are currently not compatible with Tough as Nails.

What flower are you giving to Jade? Some flowers from other mods might not work. Try giving her 5 vanilla flowers of the same kind!

**Comment by LocoMinerDad** [comment]
I gave her 5 yellow vanilla flowers, she took one. after that she started taking all 5 and giving seeds

**Comment by GirafiStudios** [comment]
That is how it is supposed to work :) The first flower is a part of the quest.
