### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kolokoro** [joshiejack/Harvest-Moon#76]
Hi!
 When I was starting my Minecraft game, I tried to start the game with this mod, and this is what happenend.
https://gist.github.com/Kolokoro/d59cbaa2b275b6dfeb242cfb48432bb6

 If you could tell me how to fix this, I would appreciate it very much. Thnaks!
Btw, my forge version is
1.10.2 - 12.18.2.2099

**Comment by GirafiStudios** [comment]
Updating to latest version of Forge should fix this :)

**Comment by Kolokoro** [comment]
I updated to the latest version of forge, but I got the same message again.

**Comment by joshiejack** [comment]
Can i see the full log pls, there is no useful information there. Make sure all your mods are for 1.10.2

**Comment by Kolokoro** [comment]
Where do I find the first logs? I'm sorry, I'm kinda dumb at these type of things.

**Comment by Kolokoro** [comment]
Is this it?

https://gist.github.com/Kolokoro/6f3f72226ab7265203f0eed95f3c344f

**Comment by GirafiStudios** [comment]
@Kolokoro no that is not the log. That would be in your logs folder in wherever you have your Forge instance with HF in it :)

**Comment by joshiejack** [comment]
If there's no response in a couple days, I'll close this.
