### ISSUE TITLE
Cucumbers (and presumably other food in the mod) don't count towards spice of life diminishing returns!

### ISSUE THREAD

**Issue by BionicFelps** [joshiejack/Harvest-Moon#81]
Currently on version 0.5.8, so this could be already fixed, but I don't see it on change notes...

I threw spice of life in my pack because I thought with all this extra food it made sense to encourage folks to eat a variety, not to mention you can also heal your hunger bar just by sleeping!

But the food in the mod doesn't seem to trigger the diminishing returns.  Also if the hunger bar is completely empty the bed fails to fill it for some reason, presumably because the damage tick wakes you out of it >.>

**Comment by joshiejack** [comment]
Need to switch to using a different method for the food to work it looks like. Easy enough to do. Not sure why it would be failing to fill you though. Only way is if the event wasn't getting fired. So not something I could fix.
