### ISSUE TITLE
Crafttweaker duplicates Shopoffers

### ISSUE THREAD

**Issue by gilfort** [joshiejack/Harvest-Moon#83]
I used the mods.harvestfestival method to implement 2 new items for the general store. 
(mods.harvestfestival.Shops.addPurchasable("harvestfestival:general", minecraft:egg, 50);
mods.harvestfestival.Shops.addPurchasable("harvestfestival:general", minecraft:apple, 25);)

As soon as i use /mt reload there will be a warning, that these items have been registered again with a different id and after that they will be doubled in the shop.
Jaredlll08 commented, that this problem is on your side and he has nothing to do with it. 

latest.log:[](http://pastebin.com/8t3VZ5zx)
latest_client.log: [](https://paste.ee/p/3Yuv3)
used Forge-version: forge-12.18.2.2106
used Crafttweakerversion CraftTweaker_1.10.2-3.0.12

**Comment by joshiejack** [comment]
Partially probably, but he should probably fix that thing where apply gets called multiple times when it shouldn't too
