### ISSUE TITLE
Better Questing Compat

### ISSUE THREAD

**Issue by squirrelkiller** [joshiejack/Harvest-Moon#84]
Better Questing is one of the better HQM alternatives. Especially with it having a nice modular API for mod compatible to be added. Making it one of those lovely pack builder tools everyone loves.

Some things I'd like to be able to do with it:

Cash rewards for quests
Track NPC relationships as a task
Cash spent
NPC relationship boosts for doing their quests
Track buildings I built as tasks
Track how deep in the mine you are as task
Track shipments as task

**Comment by joshiejack** [comment]
I can't see myself ever doing this, especially since I find the interface for better questing convoluted so don't want to have to look at it while adding support.

**Comment by joshiejack** [comment]
As I mentioned. Can't see myself doing this so just going to close it.
