### ISSUE TITLE
Snow removal deletes non-snow blocks

### ISSUE THREAD

**Issue by tobi1449** [joshiejack/Harvest-Moon#85]
The improved snow removal replaces blocks that have been placed on snow during winter.

Steps to reproduce:
1. Set season to winter
2. Set weather to snow and wait for some snow to build up
3. Place something on a snow tile (and thus replace the tile with a new block)
4. Go to sleep

The now placed block gets replaced with air 

Happens on the latest HF version (0.5.10) using Forge 12.18.2.2094

**Comment by joshiejack** [comment]
Woops and fixed. Guess this is an important enough bug to release .11 \o/

**Comment by tobi1449** [comment]
Thanks for that very fast fix. My friend thought he was going crazy because all his stuff kept disappearing xD
