### ISSUE TITLE
[Mod Compatibility]Custom NPC's Compatibility

### ISSUE THREAD

**Issue by GazbonicAcid** [joshiejack/Harvest-Moon#86]
I would like to request you add compatibility for the [Custom NPC's mod](https://minecraft.curseforge.com/projects/custom-npcs?gameCategorySlug=mc-mods&projectID=221826) to allow pack authors and server owners able to create their own pseudo custom Harvest Festival NPC's.
At least add the ability to make a Custom NPC that can trade for Harvest Festival gold as well as have their own Harvest Festival gold balance.
And possibly able to set the hire price of an NPC to a Harvest Festival gold balance,
as well as the ability for the "employer" of a hired npc to withdraw their hired npc's Harvest Festival gold balance.

**Comment by joshiejack** [comment]
If I'm being honest, I have no interest in doing this myself. If you can find someone else who'd be willing to it's fine. But it's not something I want to spend my own time on.
