### ISSUE TITLE
SkyBlendColour crashes on worldload

### ISSUE THREAD

**Issue by gilfort** [joshiejack/Harvest-Moon#87]
The world i was loading just crashed the client with this crash: 
https://paste.ee/p/qZCAi#

it never happend before and i don't know if there is a way to reproduce it.

**Comment by joshiejack** [comment]
How did you load the world? 

Although could just be random.

**Comment by gilfort** [comment]
I loaded the world as normal singleplayer world. It was a superflat world where i was testing things before. I just tested and it seems like i can't open any world in the pack right now without a crash, I'm collecting a few data and post them here in a moment

**Comment by joshiejack** [comment]
Did you add any menu altering mods? Something is making the client trackers not load. Sky colour just happens to be the first thing that calls it.

**Comment by gilfort** [comment]
I have non installed, and i also didn't add anything between the world normal loading, and the crashes

**Comment by gilfort** [comment]
This one is not the same as before - crashed while trying to generate a normal terrain world
https://paste.ee/p/kMHdA

**Comment by gilfort** [comment]
Lets take everything back - i found the issue: 
I was adding a custom loot-table for iron-golems and did a mistake there 
why this translates so critical into the game, and moreover why it mentions your mod in the reports are quite mysterious, but as soon as the loot-table is fixed, everything works again.

**Comment by joshiejack** [comment]
Heh, that's weird

**Comment by joshiejack** [comment]
Did that break the sky stuff too, if so pls close the issue
