### ISSUE TITLE
Placement of trapdoors not 100

### ISSUE THREAD

**Issue by MoonCutter2B** [joshiejack/Harvest-Moon#91]
Hi!
Not sure if this has been reported before or not and/or if it is a problem with this mod or something else but:
- the trapdoor above the ladder in the carpenters house makes it very hard to reach jennie (?) if she is upstairs. I removed and replaced it manually facing the other way so that it opens up against the wall and not against the room.
- Something simular happens with the door into the general store. It looks like trying to open the door triggers the trapdoors on the walls inside and outside by the doos and they trigger the door to close again. I.e. makes it impossile to get out or in. I tried t remove the door and replace it but failed for unknown reasons. Will try again soon, and check any logs.

1.10.2, 0.5.12, latest forge 2107, and a bunch of other mods.

**Comment by joshiejack** [comment]
Trapdoor one takes getting used to, it's easy really face the wall, climb the ladder, stand on ladder and jump. I have never had an issue with the general store though, either way blame @Yulife

**Comment by joshiejack** [comment]
I've rotated it in the carpenter for next update
