### ISSUE TITLE
game crashing

### ISSUE THREAD

**Issue by req66** [joshiejack/Harvest-Moon#93]
[crash-2016-10-24_14.10.45-server.txt](https://github.com/PenguinSquad/Harvest-Festival/files/547234/crash-2016-10-24_14.10.45-server.txt)
latest forge, minecraft 10.2, latest mod version

**Comment by joshiejack** [comment]
Under what circumstance does this happen as this report is useless without context as it references vanilla code only. Try increasing the amount of memory you're giving to minecraft, your max is way too low.

**Comment by joshiejack** [comment]
No reply so closing.
