### ISSUE TITLE
Price Changing

### ISSUE THREAD

**Issue by Rozzers** [joshiejack/Harvest-Moon#96]
I love the mod and I hope it continues to grow and improve.

After playing the mod for a while. My friends and I find the prices for the blueprints a little low. Would be great if we could change the prices of items sold by specific shops, whether through a config or minetweaker. 

I have some more friends wanting to play with my buddies and I. I would want them to use Harvest Festival as a core part of their play through and I think having the ability to change the prices would help in that.

**Comment by joshiejack** [comment]
Was added recently, so closing! :)
