### ISSUE TITLE
Typos/Grammar issues

### ISSUE THREAD

**Issue by kd8lvt** [joshiejack/Harvest-Moon#97]
"I could not **me** happier right now"  - Johan

The first time I clicked on him he said that, so I don't know if it's one of his his idle texts, or just the first time you speak to him. It's nothing major, but good to know nonetheless :)

Screenshot: [https://gyazo.com/fa1c5d5aaf0a1846fc5a4659e95f01d7](https://gyazo.com/fa1c5d5aaf0a1846fc5a4659e95f01d7)

**Comment by joshiejack** [comment]
There's loads of typos especially when i'm writing lots at a time.  I'm going to rename this issue. So we can collect all of them in one place.
