### ISSUE TITLE
Maven only has builds yet to be released

### ISSUE THREAD

**Issue by GazbonicAcid** [joshiejack/Harvest-Moon#99]
The maven server only has builds that have yet to be released on CurseForge for Minecraft 1.10.2.
This makes it impossible to make an addon mod sepecifically for versions of Harvest Festival currently available on CurseForge.

**Comment by joshiejack** [comment]
Use the ones that are 0.5, ie this http://joshiejack.uk/maven/uk/joshiejack/harvest/Harvest-Festival/1.10.2-0.5.8-94/

**Comment by GazbonicAcid** [comment]
Sorry for my confusion.
I misread some stuff.
It doesn't have builds for the most recent versions of HF,
instead of what I originally thought.
Unless that just doesn't matter for implementing the api?

**Comment by joshiejack** [comment]
It shouldn't, don't believe i changed anything within 0.5

**Comment by GazbonicAcid** [comment]
so the api's the same in 0.5.14 as it was in 0.5.8 (0.5.8 being the latest 0.5 on Maven)?
Just asking to super paranoid-level make sure.

**Comment by joshiejack** [comment]
I can do a latest 0.5 build if you want

**Comment by GazbonicAcid** [comment]
that would be awesome, thanks... :)

**Comment by joshiejack** [comment]
http://joshiejack.uk/maven/uk/joshiejack/harvest/Harvest-Festival/1.10.2-0.5.14-100/
